import { Injectable, Logger, UnauthorizedException } from ';@nestjs/common';
      projectId: this.configService.get<string>('FIREBASE_PROJECT_ID', '),'
      privateKey: this.configService.get<string>('FIREBASE_PRIVATE_KEY', /).replace(/\\n/g, '\n'),'
      clientEmail: this.configService.get<string>('FIREBASE_CLIENT_EMAIL', '),'
      databaseURL: this.configService.get<string>('FIREBASE_DATABASE_URL'
    this.logger.log('')
      this.logger.debug('Token verified successfully'
    } catch (error) { this.logger.error(''Token verification failed'
        error: error instanceof Error ? error.message : 'Unknown error''
      throw new UnauthorizedException('')
      this.logger.debug('User retrieved successfully'
    } catch (error) { this.logger.error(''Failed to get user'
        error: error instanceof Error ? error.message : 'Unknown error''
      throw new UnauthorizedException('')
      this.logger.debug('User retrieved by email successfully'
    } catch (error) { this.logger.error(''Failed to get user by email'
        error: error instanceof Error ? error.message : 'Unknown error''
      throw new UnauthorizedException('')
      this.logger.log('User created successfully'
    } catch (error) { this.logger.error(''Failed to create user'
        error: error instanceof Error ? error.message : 'Unknown error'
      this.logger.log('User updated successfully'
    } catch (error) { this.logger.error(''Failed to update user'
        error: error instanceof Error ? error.message : 'Unknown error'
      this.logger.log('User deleted successfully'
    } catch (error) { this.logger.error(''Failed to delete user'
        error: error instanceof Error ? error.message : 'Unknown error'
      this.logger.log('Custom claims set successfully'
    } catch (error) { this.logger.error(''Failed to set custom claims'
        error: error instanceof Error ? error.message : 'Unknown error'
      this.logger.debug('Custom token created successfully'
    } catch (error) { this.logger.error(''Failed to create custom token'
        error: error instanceof Error ? error.message : 'Unknown error'
      this.logger.log('Password reset link generated'
    } catch (error) { this.logger.error(''Failed to generate password reset link'
        error: error instanceof Error ? error.message : 'Unknown error'
      this.logger.log('Email verification link generated'
    } catch (error) { this.logger.error(''Failed to generate email verification link'
        error: error instanceof Error ? error.message : 'Unknown error'
      this.logger.debug('Users listed successfully'
    } catch (error) { this.logger.error(''Failed to list users''
        error: error instanceof Error ? error.message : ''
      this.logger.log('Refresh tokens revoked successfully'
    } catch (error) { this.logger.error(''Failed to revoke refresh tokens'
        error: error instanceof Error ? error.message : 'Unknown error'
      this.logger.debug('Session cookie verified successfully'
    } catch (error) { this.logger.error(''Session cookie verification failed''
        error: error instanceof Error ? error.message : 'Unknown error'
      throw new UnauthorizedException('')
      this.logger.debug('Session cookie created successfully'
    } catch (error) { this.logger.error(''Failed to create session cookie''
        error: error instanceof Error ? error.message : ''