"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.default = AwsBedrockLLMOptions;
import jsx_runtime_1 from 'react/jsx-runtime';
import react_1 from '@phosphor-icons/react';
import regions_1 from './regions.js';
import react_2 from 'react';
function AwsBedrockLLMOptions({ settings }) {
    const [useSessionToken, setUseSessionToken] = (0, react_2.useState)(settings?.AwsBedrockLLMConnectionMethod === "sessionToken");
    return ((0, jsx_runtime_1.jsxs)("div", { className: "w-full flex flex-col", children: [!settings?.credentialsOnly && ((0, jsx_runtime_1.jsx)("div", { className: "flex flex-col md:flex-row md:items-center gap-x-2 text-white mb-4 bg-blue-800/30 w-fit rounded-lg px-4 py-2", children: (0, jsx_runtime_1.jsxs)("div", { className: "gap-x-2 flex items-center", children: [(0, jsx_runtime_1.jsx)(react_1.Info, { size: 40 }), (0, jsx_runtime_1.jsxs)("p", { className: "text-base", children: ["You should use a properly defined IAM user for inferencing.", (0, jsx_runtime_1.jsx)("br", {}), (0, jsx_runtime_1.jsxs)("a", { href: "https://docs.anythingllm.com/setup/llm-configuration/cloud/aws-bedrock", target: "_blank", className: "underline flex gap-x-1 items-center", children: ["Read more on how to use AWS Bedrock in AnythingLLM", (0, jsx_runtime_1.jsx)(react_1.ArrowSquareOut, { size: 14 })] })] })] }) })), (0, jsx_runtime_1.jsxs)("div", { className: "flex flex-col gap-y-2", children: [(0, jsx_runtime_1.jsx)("input", { type: "hidden", name: "AwsBedrockLLMConnectionMethod", value: useSessionToken ? "sessionToken" : "iam" }), (0, jsx_runtime_1.jsxs)("div", { className: "flex flex-col w-full", children: [(0, jsx_runtime_1.jsx)("label", { className: "text-theme-text-primary text-sm font-semibold block mb-3", children: "Use session token" }), (0, jsx_runtime_1.jsx)("p", { className: "text-theme-text-secondary text-sm", children: "Select the method to authenticate with AWS Bedrock." })] }), (0, jsx_runtime_1.jsxs)("div", { className: "flex items-center justify-start gap-x-4 bg-theme-settings-input-bg p-2.5 rounded-lg w-fit", children: [(0, jsx_runtime_1.jsx)("span", { className: `text-sm ${!useSessionToken
                                    ? "text-theme-text-primary"
                                    : "text-theme-text-secondary"}`, children: "IAM" }), (0, jsx_runtime_1.jsxs)("label", { className: "relative inline-flex items-center cursor-pointer", children: [(0, jsx_runtime_1.jsx)("input", { type: "checkbox", className: "sr-only peer", checked: useSessionToken, onChange: (e) => setUseSessionToken(e.target.checked) }), (0, jsx_runtime_1.jsx)("div", { className: "w-11 h-6 bg-[#4b5563] light:bg-[#e5e7eb] peer-focus:outline-none rounded-full peer peer-checked:after:translate-x-full after:content-[''] after:absolute after:top-[2px] after:left-[2px] after:bg-[#d1d5db] light:after:bg-white after:rounded-full after:h-5 after:w-5 after:transition-all peer-checked:bg-primary-button" })] }), (0, jsx_runtime_1.jsx)("span", { className: `text-sm ${useSessionToken
                                    ? "text-theme-text-primary"
                                    : "text-theme-text-secondary"}`, children: "Session Token" })] })] }), (0, jsx_runtime_1.jsxs)("div", { className: "w-full flex items-center gap-[36px] my-1.5", children: [(0, jsx_runtime_1.jsxs)("div", { className: "flex flex-col w-60", children: [(0, jsx_runtime_1.jsx)("label", { className: "text-white text-sm font-semibold block mb-3", children: "AWS Bedrock IAM Access ID" }), (0, jsx_runtime_1.jsx)("input", { type: "password", name: "AwsBedrockLLMAccessKeyId", className: "border-none bg-theme-settings-input-bg text-white placeholder:text-theme-settings-input-placeholder text-sm rounded-lg focus:outline-primary-button active:outline-primary-button outline-none block w-full p-2.5", placeholder: "AWS Bedrock IAM User Access ID", defaultValue: settings?.AwsBedrockLLMAccessKeyId ? "*".repeat(20) : "", required: true, autoComplete: "off", spellCheck: false })] }), (0, jsx_runtime_1.jsxs)("div", { className: "flex flex-col w-60", children: [(0, jsx_runtime_1.jsx)("label", { className: "text-white text-sm font-semibold block mb-3", children: "AWS Bedrock IAM Access Key" }), (0, jsx_runtime_1.jsx)("input", { type: "password", name: "AwsBedrockLLMAccessKey", className: "border-none bg-theme-settings-input-bg text-white placeholder:text-theme-settings-input-placeholder text-sm rounded-lg focus:outline-primary-button active:outline-primary-button outline-none block w-full p-2.5", placeholder: "AWS Bedrock IAM User Access Key", defaultValue: settings?.AwsBedrockLLMAccessKey ? "*".repeat(20) : "", required: true, autoComplete: "off", spellCheck: false })] }), useSessionToken && ((0, jsx_runtime_1.jsxs)("div", { className: "flex flex-col w-60", children: [(0, jsx_runtime_1.jsx)("label", { className: "text-theme-text-primary text-sm font-semibold block mb-3", children: "AWS Bedrock Session Token" }), (0, jsx_runtime_1.jsx)("input", { type: "password", name: "AwsBedrockLLMSessionToken", className: "border-none bg-theme-settings-input-bg text-theme-text-primary placeholder:text-theme-settings-input-placeholder text-sm rounded-lg focus:outline-primary-button active:outline-primary-button outline-none block w-full p-2.5", placeholder: "AWS Bedrock Session Token", defaultValue: settings?.AwsBedrockLLMSessionToken ? "*".repeat(20) : "", required: true, autoComplete: "off", spellCheck: false })] })), (0, jsx_runtime_1.jsxs)("div", { className: "flex flex-col w-60", children: [(0, jsx_runtime_1.jsx)("label", { className: "text-white text-sm font-semibold block mb-3", children: "AWS region" }), (0, jsx_runtime_1.jsx)("select", { name: "AwsBedrockLLMRegion", defaultValue: settings?.AwsBedrockLLMRegion || "us-west-2", required: true, className: "border-none bg-theme-settings-input-bg text-white placeholder:text-theme-settings-input-placeholder text-sm rounded-lg focus:outline-primary-button active:outline-primary-button outline-none block w-full p-2.5", children: regions_1.AWS_REGIONS.map((region) => {
                                    return ((0, jsx_runtime_1.jsxs)("option", { value: region.code, children: [region.name, " (", region.code, ")"] }, region.code));
                                }) })] })] }), (0, jsx_runtime_1.jsx)("div", { className: "w-full flex items-center gap-[36px] my-1.5", children: !settings?.credentialsOnly && ((0, jsx_runtime_1.jsxs)(jsx_runtime_1.Fragment, { children: [(0, jsx_runtime_1.jsxs)("div", { className: "flex flex-col w-60", children: [(0, jsx_runtime_1.jsx)("label", { className: "text-white text-sm font-semibold block mb-3", children: "Model ID" }), (0, jsx_runtime_1.jsx)("input", { type: "text", name: "AwsBedrockLLMModel", className: "border-none bg-theme-settings-input-bg text-white placeholder:text-theme-settings-input-placeholder text-sm rounded-lg focus:outline-primary-button active:outline-primary-button outline-none block w-full p-2.5", placeholder: "Model id from AWS eg: meta.llama3.1-v0.1", defaultValue: settings?.AwsBedrockLLMModel, required: true, autoComplete: "off", spellCheck: false })] }), (0, jsx_runtime_1.jsxs)("div", { className: "flex flex-col w-60", children: [(0, jsx_runtime_1.jsx)("label", { className: "text-white text-sm font-semibold block mb-3", children: "Model context window" }), (0, jsx_runtime_1.jsx)("input", { type: "number", name: "AwsBedrockLLMTokenLimit", className: "border-none bg-theme-settings-input-bg text-white placeholder:text-theme-settings-input-placeholder text-sm rounded-lg focus:outline-primary-button active:outline-primary-button outline-none block w-full p-2.5", placeholder: "Content window limit (eg: 4096)", min: 1, onScroll: (e) => e.target.blur(), defaultValue: settings?.AwsBedrockLLMTokenLimit, required: true, autoComplete: "off" })] })] })) })] }));
}
//# sourceMappingURL=index.js.map