import * as React from "react";
import * as SelectPrimitive from "@radix-ui/react-select";
declare const Select: React.FC<SelectPrimitive.SelectProps>;
declare const SelectGroup: React.ForwardRefExoticComponent<SelectPrimitive.SelectGroupProps & React.RefAttributes<HTMLDivElement>>;
declare const SelectValue: React.ForwardRefExoticComponent<SelectPrimitive.SelectValueProps & React.RefAttributes<HTMLSpanElement>>;
declare const SelectTrigger: React.ForwardRefExoticComponent<React.RefAttributes<unknown>>;
declare const SelectContent: React.ForwardRefExoticComponent<React.RefAttributes<unknown>>;
declare const SelectItem: React.ForwardRefExoticComponent<React.RefAttributes<unknown>>;
declare const SelectLabel: React.ForwardRefExoticComponent<React.RefAttributes<unknown>>;
declare const SelectSeparator: React.ForwardRefExoticComponent<React.RefAttributes<unknown>>;
export { Select, SelectGroup, SelectValue, SelectTrigger, SelectContent, SelectItem, SelectLabel, SelectSeparator, };
