import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Outlet, Link, useLocation } from 'react-router-dom';
import { FileText, Video, HelpCircle, MessageSquare, Users, ChevronLeft, Search } from 'lucide-react';
/**
 * Layout for help and support pages
 */
var HelpLayout = function () {
    var location = useLocation();
    // Help navigation items
    var helpNavItems = [
        { name: 'Documentation', icon: FileText, href: '/help/documentation', current: location.pathname === '/help/documentation' },
        { name: 'Tutorials', icon: Video, href: '/help/tutorials', current: location.pathname === '/help/tutorials' },
        { name: 'FAQ', icon: HelpCircle, href: '/help/faq', current: location.pathname === '/help/faq' },
        { name: 'Support', icon: MessageSquare, href: '/help/support', current: location.pathname === '/help/support' },
        { name: 'Community', icon: Users, href: '/help/community', current: location.pathname === '/help/community' },
    ];
    return (_jsxs("div", { className: "min-h-screen bg-gray-100", children: [_jsx("div", { className: "bg-white shadow", children: _jsx("div", { className: "max-w-7xl mx-auto px-4 sm:px-6 lg:px-8", children: _jsxs("div", { className: "flex justify-between h-16", children: [_jsx("div", { className: "flex", children: _jsx("div", { className: "flex-shrink-0 flex items-center", children: _jsxs(Link, { to: "/dashboard", className: "flex items-center text-blue-600 hover:text-blue-800", children: [_jsx(ChevronLeft, { className: "h-5 w-5 mr-1" }), _jsx("span", { className: "font-medium", children: "Back to Dashboard" })] }) }) }), _jsx("div", { className: "flex items-center", children: _jsx("h1", { className: "text-xl font-semibold text-gray-900", children: "Help & Support" }) })] }) }) }), _jsxs("div", { className: "max-w-7xl mx-auto py-6 sm:px-6 lg:px-8", children: [_jsx("div", { className: "mb-6", children: _jsxs("div", { className: "relative", children: [_jsx("div", { className: "absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none", children: _jsx(Search, { className: "h-5 w-5 text-gray-400" }) }), _jsx("input", { type: "text", className: "block w-full pl-10 pr-3 py-2 border border-gray-300 rounded-md leading-5 bg-white placeholder-gray-500 focus:outline-none focus:placeholder-gray-400 focus:ring-1 focus:ring-blue-500 focus:border-blue-500 sm:text-sm", placeholder: "Search help center..." })] }) }), _jsxs("div", { className: "flex flex-col md:flex-row", children: [_jsxs("div", { className: "w-full md:w-64 mb-6 md:mb-0 md:mr-6", children: [_jsxs("div", { className: "bg-white shadow rounded-lg overflow-hidden", children: [_jsx("div", { className: "px-4 py-5 sm:px-6", children: _jsx("h2", { className: "text-lg font-medium text-gray-900", children: "Help Center" }) }), _jsx("div", { className: "border-t border-gray-200", children: _jsx("nav", { className: "px-4 py-3", children: _jsx("div", { className: "space-y-1", children: helpNavItems.map(function (item) { return (_jsxs(Link, { to: item.href, className: "".concat(item.current
                                                                ? 'bg-blue-50 text-blue-600'
                                                                : 'text-gray-600 hover:bg-gray-50 hover:text-gray-900', " group flex items-center px-3 py-2 text-sm font-medium rounded-md"), children: [_jsx(item.icon, { className: "".concat(item.current ? 'text-blue-600' : 'text-gray-400 group-hover:text-gray-500', " mr-3 flex-shrink-0 h-5 w-5") }), item.name] }, item.name)); }) }) }) })] }), _jsxs("div", { className: "mt-6 bg-blue-50 rounded-lg p-4", children: [_jsx("h3", { className: "text-sm font-medium text-blue-800", children: "Need help?" }), _jsx("p", { className: "mt-2 text-sm text-blue-700", children: "Can't find what you're looking for? Contact our support team for personalized assistance." }), _jsx("div", { className: "mt-3", children: _jsxs(Link, { to: "/help/support", className: "text-sm font-medium text-blue-600 hover:text-blue-500", children: ["Contact Support ", _jsx("span", { "aria-hidden": "true", children: "\u2192" })] }) })] })] }), _jsx("div", { className: "flex-1", children: _jsx("div", { className: "bg-white shadow rounded-lg", children: _jsx("div", { className: "px-4 py-5 sm:p-6", children: _jsx(Outlet, {}) }) }) })] })] })] }));
};
export default HelpLayout;
