services:
  tnf-crawler:
    build:
      context: ./packages/web-scraping/python
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 30s
      timeout: 10s
      retries: 3
