packages:
  - apps/*
  - packages/*
  - tools/*

onlyBuiltDependencies:
  - '@firebase/util'
  - '@nestjs/core'
  - '@prisma/client'
  - '@prisma/engines'
  - '@scarf/scarf'
  - '@swc/core'
  - aws-sdk
  - bcrypt
  - bufferutil
  - electron
  - electron-winstaller
  - esbuild
  - keccak
  - prisma
  - protobufjs
  - tiny-secp256k1
  - unrs-resolver
  - utf-8-validate
