[phases.setup]
nixPkgs = ["nodejs-20_x", "pnpm"]

[variables]
NODE_VERSION = "20.19.0"

[phases.install]
cmds = [
  "cp ../../pnpm-workspace.yaml .",
  "cp ../../pnpm-lock.yaml .",
  "cp ../../package.json .",
  "pnpm install --frozen-lockfile --include=dev"
]

[phases.build]
cmds = [
  "pnpm run --filter=@the-new-fuse/ui-consolidated build",
  "pnpm run --filter=@the-new-fuse/frontend-app build"
]

[start]
cmd = "pnpm run start"