import { useState, useEffect } from 'react';

interface ResponsiveImageProps {
  src: string;
  alt: string;
  className?: string;
  sizes?: string;
  priority?: boolean;
  objectFit?: 'cover' | 'contain' | 'fill' | 'none' | 'scale-down';
  aspectRatio?: string;
}

/**
 * Responsive Image Component
 * - Lazy loads images by default
 * - Supports priority loading for above-the-fold images
 * - Automatically generates responsive srcset for different screen sizes
 * - Optimized for mobile performance
 */
export default function ResponsiveImage({
  src,
  alt,
  className = '',
  sizes = '(max-width: 375px) 100vw, (max-width: 768px) 100vw, (max-width: 1024px) 50vw, 33vw',
  priority = false,
  objectFit = 'cover',
  aspectRatio,
}: ResponsiveImageProps) {
  const [isLoaded, setIsLoaded] = useState(false);
  const [imageSrc, setImageSrc] = useState<string>('');

  // Generate responsive image sources
  const generateSrcSet = (baseSrc: string): string => {
    // In production, these would be generated by your image optimization service
    // For now, we'll use the same source for different widths
    const widths = [320, 375, 640, 768, 1024, 1440, 1920];

    return widths
      .map((width) => {
        // If you have an image optimization service, modify the URL here
        // Example: `${baseSrc}?w=${width} ${width}w`
        return `${baseSrc} ${width}w`;
      })
      .join(', ');
  };

  useEffect(() => {
    // Implement lazy loading if not priority
    if (priority) {
      setImageSrc(src);
    } else {
      // Use Intersection Observer for lazy loading
      const img = new Image();
      img.src = src;
      img.onload = () => {
        setImageSrc(src);
        setIsLoaded(true);
      };
    }
  }, [src, priority]);

  const imageClasses = `
    ${className}
    ${!isLoaded && !priority ? 'opacity-0' : 'opacity-100'}
    transition-opacity duration-300
  `.trim();

  const containerStyle = aspectRatio
    ? { aspectRatio }
    : undefined;

  return (
    <div className={`relative overflow-hidden ${aspectRatio ? '' : 'w-full h-full'}`} style={containerStyle}>
      {!isLoaded && !priority && (
        <div className="absolute inset-0 bg-muted animate-pulse" />
      )}
      <img
        src={imageSrc || src}
        alt={alt}
        className={imageClasses}
        style={{ objectFit }}
        loading={priority ? 'eager' : 'lazy'}
        decoding="async"
        // For production, uncomment the srcSet
        // srcSet={generateSrcSet(src)}
        sizes={sizes}
      />
    </div>
  );
}
