import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState, useEffect } from 'react';
/**
 * Responsive Image Component
 * - Lazy loads images by default
 * - Supports priority loading for above-the-fold images
 * - Automatically generates responsive srcset for different screen sizes
 * - Optimized for mobile performance
 */
export default function ResponsiveImage(_a) {
    var src = _a.src, alt = _a.alt, _b = _a.className, className = _b === void 0 ? '' : _b, _c = _a.sizes, sizes = _c === void 0 ? '(max-width: 375px) 100vw, (max-width: 768px) 100vw, (max-width: 1024px) 50vw, 33vw' : _c, _d = _a.priority, priority = _d === void 0 ? false : _d, _e = _a.objectFit, objectFit = _e === void 0 ? 'cover' : _e, aspectRatio = _a.aspectRatio;
    var _f = useState(false), isLoaded = _f[0], setIsLoaded = _f[1];
    var _g = useState(''), imageSrc = _g[0], setImageSrc = _g[1];
    // Generate responsive image sources
    var generateSrcSet = function (baseSrc) {
        // In production, these would be generated by your image optimization service
        // For now, we'll use the same source for different widths
        var widths = [320, 375, 640, 768, 1024, 1440, 1920];
        return widths
            .map(function (width) {
            // If you have an image optimization service, modify the URL here
            // Example: `${baseSrc}?w=${width} ${width}w`
            return "".concat(baseSrc, " ").concat(width, "w");
        })
            .join(', ');
    };
    useEffect(function () {
        // Implement lazy loading if not priority
        if (priority) {
            setImageSrc(src);
        }
        else {
            // Use Intersection Observer for lazy loading
            var img = new Image();
            img.src = src;
            img.onload = function () {
                setImageSrc(src);
                setIsLoaded(true);
            };
        }
    }, [src, priority]);
    var imageClasses = "\n    ".concat(className, "\n    ").concat(!isLoaded && !priority ? 'opacity-0' : 'opacity-100', "\n    transition-opacity duration-300\n  ").trim();
    var containerStyle = aspectRatio
        ? { aspectRatio: aspectRatio }
        : undefined;
    return (_jsxs("div", { className: "relative overflow-hidden ".concat(aspectRatio ? '' : 'w-full h-full'), style: containerStyle, children: [!isLoaded && !priority && (_jsx("div", { className: "absolute inset-0 bg-muted animate-pulse" })), _jsx("img", { src: imageSrc || src, alt: alt, className: imageClasses, style: { objectFit: objectFit }, loading: priority ? 'eager' : 'lazy', decoding: "async", 
                // For production, uncomment the srcSet
                // srcSet={generateSrcSet(src)}
                sizes: sizes })] }));
}
