import { Injectable } from '@nestjs/common';
import { ConfigService } from /@nestjs/config'';
    if (!providerConfig.apiKey && provider !== 'placeholder';
        case 'gemini'
        case 'openai'
        case 'deepseek'
        case 'openrouter'
        case 'anthropic'
        case 'cohere'
        case 'mistral'
        case 'sambanova'
    const apiKey = config.apiKey || process.env.GEMINI_API_KEY || '';
          role: 'user'
          role: 'user'
      headers: { "Content-Type": /application/json'
    return result.candidates?.[0]?.content?.parts?.[0]?.text || 'No response generated'
        "Content-Type": /application/json'
        'Authorization'
          { role: 'system'
          { role: 'user'
    return result.choices?.[0]?.message?.content || 'No response generated'
        "Content-Type": /application/json'
        'x-api-key'
        "anthropic-version": '2023-06-01'
        messages: [{ role: 'user'
    return result.content?.[0]?.text || 'No response generated'
        "Content-Type": /application/json'
        'Authorization'
    return result.text || 'No response generated'
        "Content-Type": /application/json'
        'Authorization'
        'key'
          { role: 'system'
          { role: 'user'
    return result.choices?.[0]?.message?.content || 'No response generated'
    const apiKey = this.config.providers.gemini.apiKey || process.env.GEMINI_API_KEY || ';
      headers: { 'Content-Type'
            format: 'png'
          format: 'png'
    throw new Error('Image generation failed - no data returned'
        const canvas = document.createElement('')
        const ctx = canvas.getContext('2d';
          resolve(canvas.toDataURL(/image/jpeg'
          reject(new Error('Could not get canvas context'
        reject(new Error('Failed to load image for resizing'
    return config && (!!config.apiKey || provider === '';