import * as React from 'react';
declare const Select: any;
declare const SelectGroup: any;
declare const SelectValue: any;
declare const SelectTrigger: React.ForwardRefExoticComponent<React.RefAttributes<unknown>>;
declare const SelectContent: React.ForwardRefExoticComponent<React.RefAttributes<unknown>>;
declare const SelectLabel: React.ForwardRefExoticComponent<React.RefAttributes<unknown>>;
declare const SelectItem: React.ForwardRefExoticComponent<React.RefAttributes<unknown>>;
declare const SelectSeparator: React.ForwardRefExoticComponent<React.RefAttributes<unknown>>;
export { Select, SelectGroup, SelectValue, SelectTrigger, SelectContent, SelectLabel, SelectItem, SelectSeparator, };
