
import { VectorMemoryStore } from './VectorMemoryStore';
import { MemoryItem, Vector } from './MemoryTypes';

/**
 * @interface ConversationTurn
 * @description Represents a single turn in a conversation between a user and an agent.
 *
 * @property {string} agentId - The unique identifier for the agent involved in the turn.
 * @property {Date} timestamp - The exact time when the conversation turn occurred.
 * @property {'user' | 'agent'} role - The role of the participant in the turn, either 'user' or 'agent'.
 * @property {string} content - The textual content of the conversation turn.
 * @property {number} importance - A numerical score representing the significance of the turn (e.g., for summarization or retrieval).
 */
export interface ConversationTurn {
  agentId: string;
  timestamp: Date;
  role: 'user' | 'agent';
  content: string;
  importance: number;
}

/**
 * @class ConversationMemory
 * @description Manages the storage and retrieval of conversational history for agents,
 * leveraging a vector memory system for contextually relevant information retrieval.
 *
 * @example
 * ```typescript
 * const vectorMemory = new VectorMemoryStore(); // Assuming VectorMemoryStore is initialized
 * const conversationMemory = new ConversationMemory(vectorMemory);
 *
 * const turn = {
 *   agentId: 'agent-007',
 *   timestamp: new Date(),
 *   role: 'user',
 *   content: 'What is the weather like in London?',
 *   importance: 0.8
 * };
 *
 * await conversationMemory.storeConversationTurn('session-123', turn);
 *
 * const context = await conversationMemory.getRelevantContext('session-123', 'Tell me about the climate.');
 * console.log(context);
 * ```
 */
export class ConversationMemory {
  private vectorMemory: VectorMemoryStore;

  /**
   * @constructor
   * @param {VectorMemoryStore} vectorMemory - An instance of VectorMemoryStore for handling vector-based memory operations.
   */
  constructor(vectorMemory: VectorMemoryStore) {
    this.vectorMemory = vectorMemory;
  }

  /**
   * @method storeConversationTurn
   * @description Stores a single turn of a conversation in the vector memory.
   * @param {string} sessionId - The unique identifier for the conversation session.
   * @param {ConversationTurn} turn - The conversation turn to be stored.
   * @returns {Promise<void>}
   */
  async storeConversationTurn(sessionId: string, turn: ConversationTurn): Promise<void> {
    // A placeholder embedding is created here. In a real implementation, this would
    // be generated by a dedicated embedding service. The dimensions should match
    // the configuration of the VectorMemoryStore.
    const placeholderEmbedding: Vector = Array(1536).fill(0);

    const memoryItem: MemoryItem = {
      id: `${sessionId}-${turn.timestamp.getTime()}`,
      content: turn.content,
      type: 'conversation',
      embedding: placeholderEmbedding,
      importance: turn.importance,
      metadata: {
        sessionId,
        agentId: turn.agentId,
        timestamp: turn.timestamp.toISOString(),
        role: turn.role,
      },
      timestamp: turn.timestamp.getTime()
    };
    // The addItem signature is (id, config, item). We pass the item's id and the item itself.
    await this.vectorMemory.addItem(memoryItem.id, null, memoryItem);
  }

  /**
   * @method getRelevantContext
   * @description Retrieves a list of relevant conversation turns based on a query, filtered by session.
   * The results are ordered chronologically.
   * @param {string} sessionId - The identifier for the conversation session to search within.
   * @param {string} currentQuery - The query string to find relevant context for.
   * @param {number} [limit=5] - The maximum number of conversation turns to retrieve.
   * @returns {Promise<ConversationTurn[]>} - A promise that resolves to an array of relevant conversation turns.
   */
  async getRelevantContext(sessionId: string, currentQuery: string, limit = 5): Promise<ConversationTurn[]> {
    const searchResults = await this.vectorMemory.findSimilarItems({
      text: currentQuery,
      limit,
      filters: {
        metadata: {
          sessionId,
        }
      }
    });

    const relevantTurns = searchResults
      .filter(result => result.similarity >= 0.6)
      .map(result => {
        const metadata = result.item.metadata;
        return {
          agentId: metadata.agentId as string,
          timestamp: new Date(metadata.timestamp as string),
          role: metadata.role as 'user' | 'agent',
          content: result.item.content,
          importance: result.item.importance, // Correctly retrieve importance from the item
        };
      });

    // Sort chronologically
    relevantTurns.sort((a, b) => a.timestamp.getTime() - b.timestamp.getTime());

    return relevantTurns;
  }
}
