export declare function middleTruncate(str: string, maxLength: number): string;
export declare function truncateFileExtension(filename: string): string;
export declare function getFileExtension(filename: string): string;
export declare function isImageByExtension(filename: string): boolean;
export declare function isVideoByExtension(filename: string): boolean;
export declare function isAudioByExtension(filename: string): boolean;
export declare function isPDFByExtension(filename: string): boolean;
export declare function isTextByExtension(filename: string): boolean;
export declare function normalizePath(path: string): string;
export declare function getFileName(path: string): string;
export declare function getFileNameWithoutExtension(fileName: string): string;
export declare function getDirectoryPath(path: string): string;
export declare function joinPaths(...paths: string[]): string;
export declare function isSubPath(parent: string, child: string): boolean;
export declare function getRelativePath(from: string, to: string): string;
export declare function getPathDepth(path: string): number;
export declare function getCommonPath(paths: string[]): string;
export declare function isValidFileName(fileName: string): boolean;
export declare function sanitizeFileName(fileName: string): string;
export declare function parsePathParts(path: string): {
    root: string;
    dir: string;
    name: string;
    ext: string;
};
