import { RenderResult, RenderOptions } from '@testing-library/react';
import { ReactElement } from 'react';
import { MockNode, MockEdge, MockUser, MockWorkflow, AuthContextValue, WorkflowContextValue } from '../types/test.js';
export declare const createMockNode: (overrides?: Partial<MockNode>) => MockNode;
export declare const createMockEdge: (overrides?: Partial<MockEdge>) => MockEdge;
export declare const createMockUser: (overrides?: Partial<MockUser>) => MockUser;
export declare const createMockWorkflow: (overrides?: Partial<MockWorkflow>) => MockWorkflow;
export declare const mockAuthContextValue: AuthContextValue;
export declare const mockWorkflowContextValue: WorkflowContextValue;
declare const customRender: (ui: ReactElement, options?: Omit<RenderOptions, "wrapper">) => RenderResult;
export * from '@testing-library/react';
export { customRender as render };
