export declare class A2AConfigDto {
    gatewayUrl?: string;
    apiKey?: string;
    timeout?: number;
    maxRetries?: number;
    retryDelay?: number;
    enableLogging?: boolean;
    enableMetrics?: boolean;
    enableHealthChecks?: boolean;
    allowedCapabilities?: string[];
    blockedCapabilities?: string[];
    maxMessageSize?: number;
    rateLimitWindow?: number;
    rateLimitMaxRequests?: number;
    enableAgentDiscovery?: boolean;
    enableAgentRegistration?: boolean;
    agentDiscoveryEndpoint?: string;
    agentRegistrationEndpoint?: string;
    messageExchangeEndpoint?: string;
    enableSecurity?: boolean;
    trustedAgents?: string[];
    blockedAgents?: string[];
    encryptionKey?: string;
    enableEncryption?: boolean;
    messageRetentionDays?: number;
    enableMessagePersistence?: boolean;
    persistenceProvider?: string;
    redisUrl?: string;
    databaseUrl?: string;
    enableCircuitBreaker?: boolean;
    circuitBreakerFailureThreshold?: number;
    circuitBreakerResetTimeout?: number;
    enableLoadBalancing?: boolean;
    loadBalancerEndpoints?: string[];
    loadBalancerStrategy?: string;
    enableCaching?: boolean;
    cacheTtl?: number;
    cacheMaxSize?: number;
    enableWebhooks?: boolean;
    webhookEndpoints?: string[];
    webhookSecret?: string;
    enableMetricsCollection?: boolean;
    metricsEndpoint?: string;
    enableTracing?: boolean;
    tracingEndpoint?: string;
    tracingServiceName?: string;
    enableGracefulShutdown?: boolean;
    gracefulShutdownTimeout?: number;
    enableRequestValidation?: boolean;
    enableResponseValidation?: boolean;
    enableErrorHandling?: boolean;
    enableLoggingMiddleware?: boolean;
    logLevel?: string;
    enableStructuredLogging?: boolean;
    logFormat?: string;
    enableLogRotation?: boolean;
    maxLogFiles?: number;
    maxLogFileSize?: number;
}
export declare class A2AConfig {
    private logger;
    private config;
    private configService;
    constructor();
    private loadConfig;
    get gatewayUrl(): string | undefined;
    get apiKey(): string | undefined;
    get timeout(): number;
    get maxRetries(): number;
    get retryDelay(): number;
    get enableLogging(): boolean;
    get enableMetrics(): boolean;
    get enableHealthChecks(): boolean;
    get allowedCapabilities(): string[];
    get blockedCapabilities(): string[];
    get maxMessageSize(): number;
    get rateLimitWindow(): number;
    get rateLimitMaxRequests(): number;
    get enableAgentDiscovery(): boolean;
    get enableAgentRegistration(): boolean;
    get agentDiscoveryEndpoint(): string;
    get agentRegistrationEndpoint(): string;
    get messageExchangeEndpoint(): string;
    get enableSecurity(): boolean;
    get trustedAgents(): string[];
    get blockedAgents(): string[];
    get encryptionKey(): string | undefined;
    get enableEncryption(): boolean;
    get messageRetentionDays(): number;
    get enableMessagePersistence(): boolean;
    get persistenceProvider(): string;
    get redisUrl(): string | undefined;
    get databaseUrl(): string | undefined;
    get enableCircuitBreaker(): boolean;
    get circuitBreakerFailureThreshold(): number;
    get circuitBreakerResetTimeout(): number;
    get enableLoadBalancing(): boolean;
    get loadBalancerEndpoints(): string[];
    get loadBalancerStrategy(): string;
    get enableCaching(): boolean;
    get cacheTtl(): number;
    get cacheMaxSize(): number;
    get enableWebhooks(): boolean;
    get webhookEndpoints(): string[];
    get webhookSecret(): string | undefined;
    get enableMetricsCollection(): boolean;
    get metricsEndpoint(): string;
    get enableTracing(): boolean;
    get tracingEndpoint(): string | undefined;
    get tracingServiceName(): string;
    get enableGracefulShutdown(): boolean;
    get gracefulShutdownTimeout(): number;
    get enableRequestValidation(): boolean;
    get enableResponseValidation(): boolean;
    get enableErrorHandling(): boolean;
    get enableLoggingMiddleware(): boolean;
    get logLevel(): string;
    get enableStructuredLogging(): boolean;
    get logFormat(): string;
    get enableLogRotation(): boolean;
    get maxLogFiles(): number;
    get maxLogFileSize(): number;
    isCapabilityAllowed(capability: string): boolean;
    isAgentTrusted(agentId: string): boolean;
    getAllConfig(): A2AConfigDto;
    updateConfig(updates: Partial<A2AConfigDto>): void;
}
//# sourceMappingURL=A2AConfig.d.ts.map