import { ConfigService as NestConfigService } from '@nestjs/config';
export declare class ConfigService extends NestConfigService {
    getPort(): number;
    getDatabaseUrl(): string;
    getRedisUrl(): string;
    getJwtSecret(): string;
    getEnvironment(): string;
    isDevelopment(): boolean;
    isProduction(): boolean;
    isTest(): boolean;
    getWebSocketPort(): number;
    getRedisHost(): string;
    getRedisPort(): number;
    getRedisPassword(): string | undefined;
    getRedisDb(): number;
    getDatabaseHost(): string;
    getDatabasePort(): number;
    getDatabaseName(): string;
    getDatabaseUsername(): string;
    getDatabasePassword(): string;
    getCorsOrigins(): string[];
    getJwtExpiresIn(): string;
    getApiPrefix(): string;
    getApiVersion(): string;
    getLogLevel(): string;
    isSwaggerEnabled(): boolean;
    isMetricsEnabled(): boolean;
    getOpenAIApiKey(): string | undefined;
    getCloudflareApiKey(): string | undefined;
    getFirebaseConfigPath(): string | undefined;
    getMaxAgentConcurrency(): number;
    getAgentTimeout(): number;
    getQdrantUrl(): string;
    getQdrantApiKey(): string | undefined;
    getMemoryRetentionDays(): number;
    getMemoryCapacity(): number;
    getMemoryShortTermCapacity(): number;
    getMemoryWorkingCapacity(): number;
    getMemoryLongTermRetentionDays(): number;
    getMemoryCompressionThreshold(): number;
    getMemoryEmbeddingDimension(): number;
    isMemoryClusteringEnabled(): boolean;
    isMemoryAutoOptimizeEnabled(): boolean;
    getChunkingMaxChunkSize(): number;
    getChunkingOverlap(): number;
    getChunkingProvider(): 'openai' | 'anthropic' | 'local';
    getChunkingSimilarityThreshold(): number;
    getChunkingMinChunkSize(): number;
    getCascadeApiKey(): string | undefined;
    getClineApiKey(): string | undefined;
    getCascadeModel(): string;
    getClineModel(): string;
    getMaxMemoryMessages(): number;
    getServiceDiscoveryEnabled(): boolean;
    getMessageQueueEnabled(): boolean;
    getHealthCheckInterval(): number;
}
//# sourceMappingURL=ConfigService.d.ts.map