export const LEGAL_TEMPLATES = {
  SPONSORSHIP_DISCLAIMER: {
    title: "Sponsorship Checkout Disclaimer",
    content: "By purchasing this Agent Sponsorship SFT, you acknowledge and agree that: (1) You are purchasing a digital collectible with utility features, not a financial security or investment contract. (2) 'Revenue Yield' is contingent upon the autonomous performance of the AI Agent and market demand for its services. (3) The New Fuse (TNF) does not guarantee future earnings. (4) You are responsible for all taxes associated with on-chain income claims.",
    usage: "Must appear before User confirms SFT purchase."
  },
  AGENCY_LICENSE_AGREEMENT: {
    title: "Agency White-Label License Agreement",
    content: "Purchase of a Fuse Agency License grants the holder 'Sovereign Operator' status on the Polygon UNS Registry. The Licensee acknowledges that: (1) TNF takes 0% of revenue generated by Agency-owned agents. (2) The Licensee is solely responsible for compliance with local regulations regarding their specific 'Affiliate' and 'Investor' payout structures. (3) TNF reserves the right to blacklist Agency domains if they are found to host illegal content, in accordance with the Unstoppable Domains Anti-Abuse Policy.",
    usage: "Must appear on thenewfuse.hub before Agency License purchase."
  }
};

export const SOP_LINKS = {
  DISPUTE_RESOLUTION: "/docs/sop/dispute-resolution",
  STRIPE_FAILURE: "/docs/sop/stripe-failure",
  AGENCY_FEE_DISPUTE: "/docs/sop/agency-dispute"
};
