[phases.setup]
nixPkgs = ["nodejs_20", "pnpm"]

[variables]
NODE_VERSION = "20"

[phases.install]
cmds = ["cd apps/backend && pnpm install --frozen-lockfile"]

[phases.build]
cmds = ["cd apps/backend && pnpm run build"]

[start]
cmd = "cd apps/backend && pnpm run start:prod"