import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Box, Grid, LineChart, StatGroup, Stat, StatLabel, StatNumber, StatHelpText, Table, Thead, Tbody, Tr, Th, Td, Heading } from '@chakra-ui/react';
import { useApiMetrics } from '../../hooks/useApiMetrics';
export var ApiMonitor = function () {
    var _a = useApiMetrics(), metrics = _a.metrics, endpoints = _a.endpoints, errors = _a.errors, loading = _a.loading;
    if (loading)
        return _jsx(Box, { children: "Loading metrics..." });
    return (_jsxs(Box, { children: [_jsxs(StatGroup, { mb: 6, children: [_jsxs(Stat, { children: [_jsx(StatLabel, { children: "Total Requests" }), _jsx(StatNumber, { children: metrics.totalRequests }), _jsx(StatHelpText, { children: "Last 24 hours" })] }), _jsxs(Stat, { children: [_jsx(StatLabel, { children: "Error Rate" }), _jsxs(StatNumber, { children: [metrics.errorRate, "%"] }), _jsx(StatHelpText, { children: "Overall" })] }), _jsxs(Stat, { children: [_jsx(StatLabel, { children: "Avg Response Time" }), _jsxs(StatNumber, { children: [metrics.avgResponseTime, "ms"] }), _jsx(StatHelpText, { children: "All endpoints" })] })] }), _jsxs(Grid, { templateColumns: "1fr 1fr", gap: 6, mb: 6, children: [_jsxs(Box, { p: 4, borderRadius: "md", boxShadow: "sm", children: [_jsx(Heading, { size: "sm", mb: 4, children: "Request Volume" }), _jsx(LineChart, { data: metrics.requestsOverTime, xKey: "timestamp", yKey: "count", height: 200 })] }), _jsxs(Box, { p: 4, borderRadius: "md", boxShadow: "sm", children: [_jsx(Heading, { size: "sm", mb: 4, children: "Response Times" }), _jsx(LineChart, { data: metrics.responseTimesOverTime, xKey: "timestamp", yKey: "value", height: 200 })] })] }), _jsx(Box, { children: _jsxs(Table, { variant: "simple", children: [_jsx(Thead, { children: _jsxs(Tr, { children: [_jsx(Th, { children: "Endpoint" }), _jsx(Th, { children: "Method" }), _jsx(Th, { children: "Requests" }), _jsx(Th, { children: "Avg Time" }), _jsx(Th, { children: "Error Rate" })] }) }), _jsx(Tbody, { children: endpoints.map(function (endpoint) { return (_jsxs(Tr, { children: [_jsx(Td, { children: endpoint.path }), _jsx(Td, { children: endpoint.method }), _jsx(Td, { children: endpoint.requests }), _jsxs(Td, { children: [endpoint.avgTime, "ms"] }), _jsxs(Td, { children: [endpoint.errorRate, "%"] })] }, "".concat(endpoint.method, "-").concat(endpoint.path))); }) })] }) })] }));
};
