import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import * as Skeleton from "react-loading-skeleton";
import "react-loading-skeleton/dist/skeleton.css";
import { isMobile } from "react-device-detect";
export default function LoadingChat() {
    var highlightColor = "var(--theme-bg-primary)";
    var baseColor = "var(--theme-bg-secondary)";
    return (_jsxs("div", { className: "transition-all duration-500 relative md:ml-[2px] md:mr-[16px] md:my-[16px] md:rounded-[16px] bg-theme-bg-secondary w-full h-full overflow-y-scroll no-scroll p-4", style: { height: "calc(100% - 32px)" }, children: [_jsx(Skeleton.default, { height: "100px", width: "100%", highlightColor: highlightColor, baseColor: baseColor, count: 1, className: "max-w-full md:max-w-[80%] p-4 rounded-b-2xl rounded-tr-2xl rounded-tl-sm mt-6", containerClassName: "flex justify-start" }), _jsx(Skeleton.default, { height: "100px", width: isMobile ? "70%" : "45%", baseColor: baseColor, highlightColor: highlightColor, count: 1, className: "max-w-full md:max-w-[80%] p-4 rounded-b-2xl rounded-tr-2xl rounded-tl-sm mt-6", containerClassName: "flex justify-end" }), _jsx(Skeleton.default, { height: "100px", width: isMobile ? "55%" : "30%", baseColor: baseColor, highlightColor: highlightColor, count: 1, className: "max-w-full md:max-w-[80%] p-4 rounded-b-2xl rounded-tr-2xl rounded-tl-sm mt-6", containerClassName: "flex justify-start" }), _jsx(Skeleton.default, { height: "100px", width: isMobile ? "88%" : "25%", baseColor: baseColor, highlightColor: highlightColor, count: 1, className: "max-w-full md:max-w-[80%] p-4 rounded-b-2xl rounded-tr-2xl rounded-tl-sm mt-6", containerClassName: "flex justify-end" }), _jsx(Skeleton.default, { height: "160px", width: "100%", baseColor: baseColor, highlightColor: highlightColor, count: 1, className: "max-w-full md:max-w-[80%] p-4 rounded-b-2xl rounded-tr-2xl rounded-tl-sm mt-6", containerClassName: "flex justify-start" })] }));
}
