import { jsx as _jsx } from "react/jsx-runtime";
export const Card = ({ children, ...props }) => (_jsx("div", { ...props, children: children }));
const Header = ({ children, ...props }) => (_jsx("div", { ...props, children: children }));
const Title = ({ children, ...props }) => (_jsx("div", { ...props, children: children }));
const Description = ({ children, ...props }) => (_jsx("div", { ...props, children: children }));
const Content = ({ children, ...props }) => (_jsx("div", { ...props, children: children }));
const Footer = ({ children, ...props }) => (_jsx("div", { ...props, children: children }));
// Attach subcomponents as static properties
Card.Header = Header;
Card.Title = Title;
Card.Description = Description;
Card.Content = Content;
Card.Footer = Footer;
const CardWithStatics = Card;
CardWithStatics.Header = Header;
CardWithStatics.Title = Title;
CardWithStatics.Description = Description;
CardWithStatics.Content = Content;
CardWithStatics.Footer = Footer;
export { Header, Title, Description, Content, Footer, Header as CardHeader, Title as CardTitle, Description as CardDescription, Content as CardContent, Footer as CardFooter };
export default CardWithStatics;
