# Use the official Bun image as a base image
FROM oven/bun:1.0.18-alpine

# Set the working directory
WORKDIR /app

# Copy the package.json and bun.lockb files to the working directory
COPY package.json bun.lockb ./

# Install dependencies
RUN bun install --frozen-lockfile

# Copy the rest of the application code to the working directory
COPY . .

# Expose the port that the application will run on
EXPOSE 3002

# Start the application
CMD ["bun", "run", "start:message-broker"]