import { WorkflowTemplate, WorkflowStepType, WorkflowStep } from '';
  id: 'ai-diplomacy-agentic-flow'
  name: 'AI Diplomacy Agentic Flow'
  description: 'Detailed agentic workflow for AI Diplomacy, including context construction, memory, diaries, and phase transitions.'
  version: ''
    startStep: 'context-construction'
      id: 'context-construction'
      name: 'Context Construction'
          'Game State Information'
          'Memory System'
          'Dynamic Goals'
          'Relationships'
          'Private Diary'
          'Negotiation Diary'
          'Order Diary'
          'Phase Result Diary'
          'Diary Consolidation'
          'Private Journal'
          'Possible Order Context'
          'build_context_prompt'
          'Recent Context'
      status: ''
      id: 'initialization'
        action: 'Set initial goals & relationships'
      dependencies: ['context-construction'
      status: ''
      id: 'negotiation'
        action: 'Generate messages, update relationships'
      dependencies: ['initialization'
      status: ''
      id: 'negotiation-diary'
      name: 'Negotiation Diary'
          'Message Analysis'
          'Trust Assessment'
          'Relationship Changes'
      dependencies: ['negotiation'
      status: ''
      id: 'planning'
        action: 'Strategic directives'
      dependencies: ['negotiation-diary'
      status: ''
      id: 'order-generation'
      name: 'Order Generation'
        action: 'Choose moves'
      dependencies: ['planning'
      status: ''
      id: 'order-diary'
      name: 'Order Diary'
          'Strategic Reasoning'
          /Risk/Reward Analysis'
      dependencies: ['order-generation'
      status: ''
      id: 'state-update'
      name: 'State Update'
        action: 'Revise goals & relationships'
      dependencies: ['order-diary'
      status: ''
      id: 'phase-result-diary'
      name: 'Phase Result Diary'
          'Outcome Analysis'
          'Betrayal Detection'
          'Success Evaluation'
      dependencies: ['state-update'
      status: ''
      id: 'diary-consolidation'
      name: 'Diary Consolidation'
          'Phase Summary'
          'Successful Moves'
          'Failed Moves'
          'Board Changes'
          'Yearly summaries via Gemini Flash'
      dependencies: ['phase-result-diary'
      status: ''
      id: 'memory-update'
      name: 'Memory System Update'
          'Summarized Game State'
          'Game History'
          'Phase Summary'
          'Dynamic Goals'
          'Relationships'
          'Private Diary'
          'Negotiation Diary'
          'Order Diary'
          'Phase Result Diary'
          'Diary Consolidation'
          'Private Journal'
      dependencies: ['diary-consolidation'
      status: ''
      id: 'loop'
      name: 'Loop to Next Phase'
        action: 'Return to Negotiation for next phase'
      dependencies: ['memory-update'
      status: ''