[build]
builder = "DOCKERFILE"
dockerfilePath = "packages/relay-core/Dockerfile"
watchPaths = ["packages/relay-core/**", "packages/types/**", "packages/core/**"]

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyMaxRetries = 10
restartPolicyType = "ON_FAILURE"