name = "tnf-sharedstate"
main = "src/index.ts"
compatibility_date = "2026-02-09"

account_id = "db1d3832768b2bbad4c5c5d9dbc63f8b"
workers_dev = true
preview_urls = false

[vars]
ENVIRONMENT = "dev"

[[r2_buckets]]
binding = "SHAREDSTATE_BUCKET"
bucket_name = "tnf-sharedstate"

[[d1_databases]]
binding = "SHAREDSTATE_DB"
database_name = "tnf_sharedstate"
database_id = "c9581c73-982e-4e67-8d71-d91fc0107bc4"

[durable_objects]
bindings = [
  { name = "RECEIPT_SEQ", class_name = "ReceiptSequencer" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["ReceiptSequencer"]
