import { Injectable, Logger } from '@nestjs/common';
        where: { type: 'general'
      this.logger.error('')
        where: { type: 'general'
          type: 'general'
      this.logger.error('')
      this.logger.error('')
      this.logger.error('')
        where: { type: 'steps'
      this.logger.error('')
        where: { type: 'steps'
          type: 'steps'
      this.logger.error('')
      this.logger.error('')
      this.logger.error('')
        issues.push('Welcome title is required in general settings'
        issues.push('')
        issues.push('')
        issues.push('')
      const hasWelcomeStep = steps.some(step => step.type === welcome';
        issues.push('A welcome step is required'
      const hasCompletionStep = steps.some(step => step.type === completion';
        issues.push('')
          issues.push('Default embedding model is required when RAG is enabled'
          issues.push('')
          issues.push('Greeter agent name is required when greeter agent is enabled'
          issues.push('')
        warnings.push('Having more than 7 steps may lead to user fatigue'
      if (steps.filter(step => step.userTypes.includes('ai_agent';
        warnings.push('')
        status: issues.length > 0 ? error": warnings.length > 0 ? warning' : 'success'
          ? Configuration has 'errors'
            ? Configuration has "warnings":Configuration is valid'
      this.logger.error('')
          { step: 'profile'
          { step: 'ai_preferences'
          { step: 'workspace'
          { type: 'human'
          { type: 'ai_agent'
      this.logger.error('')
      logoUrl:/assets/images/logo.'png'
      primaryColor:#3182'CE'
      secondaryColor:#4'FD1C5'
      welcomeTitle: Welcome to The New 'Fuse'
      redirectAfterCompletion: /'
        id: 'human'
        name: Human 'User'
        description:Regular human users of the platform'
        detectionMethod: 'behavior'
          behaviorPattern: human-like interaction 'patterns'
        onboardingFlow: 'human'
        id: 'ai_agent'
        name:AI Agent'
        description:AI agents that integrate with the platform'
        detectionMethod: 'header'
        onboardingFlow: ''
        type: 'welcome'
        description:Introduction to The New Fuse platform'
        userTypes: ['human', ai_agent'
          heading:Welcome to The New Fuse'
          imageUrl: /assets/images/welcome.'png'
          buttonText:Get Started'
        id:2'
        type: 'profile'
        title:User Profile'
        description:Collect user information'
        userTypes: ['human'
          heading:Tell us about yourself'
          subheading:This information helps us personalize your experience.'
        type: 'ai_preferences'
        title: AI 'Preferences'
        description:Configure AI settings'
        userTypes: ['human'
          heading:AI Preferences'
          subheading:Configure how AI agents work for you.'
        type: 'workspace'
        title: Workspace 'Setup'
        description:Set up workspace preferences'
        userTypes: ['human', ai_agent'
          heading:Set Up Your Workspace'
          subheading:Configure your workspace to suit your needs.'
        type: 'tools'
        title: Tools & 'Integrations'
        description:Select tools and integrations'
        userTypes: ['human'
          heading:Tools & Integrations'
          subheading:Select the tools you want to use with The New Fuse.'
        type: 'greeter'
        title: Meet Your 'Assistant'
        description:Introduction to the Greeter Agent'
        userTypes: ['human'
          heading:Meet Your Assistant'
          subheading:Your AI assistant will help you navigate The New Fuse.'
        type: 'completion'
        description:Onboarding completion'
        userTypes: ['human', ai_agent'
          heading:All Set!'
          subheading: You\'re ready to start using The New Fuse.'
      vectorDatabaseType: 'pinecone'
        pineconeIndex: ''
      defaultLLMProvider: 'openai'
      defaultLLMModel: gpt-4'
      greeterAgentAvatar:/assets/images/greeter-avatar.'png'
      greeterAgentPrompt:You are Fuse Assistant, a helpful AI assistant designed to help users get started with The New Fuse platform. Your goal is to be friendly, informative, and guide users through the onboarding process.'
          id: kb-1'
          name:Platform Overview'
          description:General information about The New Fuse platform'
          id:kb-2'
          name: Getting Started 'Guide'
          description:Step-by-step guide for new users'
          id:kb-3'
          description:Frequently asked questions'
      supportedModalities: ['text', image'