mermaid
graph TD
  subgraph "10/15/2021"
    msg0["'TheRealTuna', great name!..."]
  end
  msg1["Just updated my username with ! But I alas, I will..."]
  msg0 --> msg1
  msg2["Any way around these gas fees while swapping ETH f..."]
  msg1 --> msg2
  msg3["Costs the same gas fees no matter which rout I try..."]
  msg2 --> msg3
  msg4["I ran into some problems trying to deposit on V4. ..."]
  msg3 --> msg4
  msg5["I ran into some problems trying to deposit on V4. ..."]
  msg4 --> msg5
  msg6["StarTreeTV🌊🏆
POOL Hodler
 — 
10/15/21, 7:55 PM
F..."]
  msg5 --> msg6
  msg7["Not sure if this last error was part of same trans..."]
  msg6 --> msg7
  msg8["OK, good idea, I tried it. It shows 2 pending tran..."]
  msg7 --> msg8
  msg9["Which one should I try and cancel? But also, cance..."]
  msg8 --> msg9
  msg10["Well, being that it has cost me like 4x the amount..."]
  msg9 --> msg10
  msg11["Yeah, but gas fees every time converting it from M..."]
  msg10 --> msg11
  msg12["StarTreeTV🌊🏆
POOL Hodler
 — 
10/15/21, 8:21 PM
F..."]
  msg11 --> msg12
  msg13["I have been absolutely killing myself with all the..."]
  msg12 --> msg13
  msg14["How come when I push to cancel transaction, does i..."]
  msg13 --> msg14
  msg15["StarTreeTV🌊🏆
POOL Hodler
 — 
10/15/21, 8:56 PM
F..."]
  msg14 --> msg15
  msg16["Thanks for confirming...."]
  msg15 --> msg16
  msg17["When you said, 'straight to matic'? How? I haven't..."]
  msg16 --> msg17
  subgraph "10/16/2021"
    msg18["If anyone is willing to try and send me $0.02 wort..."]
  end
  msg17 --> msg18
  msg19["StarTreeTV🌊🏆
POOL Hodler
 — 
10/16/21, 1:36 PM
S..."]
  msg18 --> msg19
  msg20["OK..."]
  msg19 --> msg20
  msg21["Thanks much for your timely help, Leighton, it wor..."]
  msg20 --> msg21
  subgraph "12/1/2021"
    msg22["I think this is an Awesome change! Very exciting! ..."]
  end
  msg21 --> msg22
  msg23["I think this is an Awesome change! Very exciting! ..."]
  msg22 --> msg23
  msg24["Just in case people didn't see the news in the dev..."]
  msg23 --> msg24
  subgraph "12/4/2021"
    msg25["Markets crashing...Not good!..."]
  end
  msg24 --> msg25
  msg26["Is there a way to find out if I have been nominate..."]
  msg25 --> msg26
  msg27["Is there a way to find out if I have been nominate..."]
  msg26 --> msg27
  msg28["I saw that I had a few give allocated, but wasn't ..."]
  msg27 --> msg28
  subgraph "12/6/2021"
    msg29["GM team..."]
  end
  msg28 --> msg29
  msg30["How about a thread called #ideas or #inovation ?..."]
  msg29 --> msg30
  msg31["'swim-team' is quite a vague thread title IMHO. Bu..."]
  msg30 --> msg31
  msg32["Yeah, I mean if the idea is to actually get more p..."]
  msg31 --> msg32
  msg33["My impetus was to find the correct place to post j..."]
  msg32 --> msg33
  msg34["I am not sure what each should definitely be calle..."]
  msg33 --> msg34
  msg35["Sorry, I should have made my last 2 responses inst..."]
  msg34 --> msg35
  msg36["I think it is an area that can be improved upon gi..."]
  msg35 --> msg36
  msg37["Much easier to understand! :)..."]
  msg36 --> msg37
  msg38["I  can't unmute..."]
  msg37 --> msg38
  subgraph "12/23/2021"
    msg39["Also this one: ⁠general⁠..."]
  end
  msg38 --> msg39
  msg40["⁠general⁠..."]
  msg39 --> msg40
  msg41["⁠governance⁠..."]
  msg40 --> msg41
  msg42["⁠governance⁠..."]
  msg41 --> msg42
  msg43["⁠governance⁠..."]
  msg42 --> msg43
  msg44["Is there any way to incorporate https://brokoli.ne..."]
  msg43 --> msg44
  msg45["Can you expound on what you mean?..."]
  msg44 --> msg45
  msg46["What is CVX?..."]
  msg45 --> msg46
  msg47["How about a #terminology  thread or #acronyms ?..."]
  msg46 --> msg47
  msg48["'Exchange POOL tokens with a community like Cool C..."]
  msg47 --> msg48
  msg49["'Exchange POOL tokens with a community like Cool C..."]
  msg48 --> msg49
  msg50["NFTs can also be divided into fractional ownership..."]
  msg49 --> msg50
  msg51["So, if POOL was exchanged for valuable NFTs, those..."]
  msg50 --> msg51
  msg52["Thanks. Sounds promising! I found this:https://you..."]
  msg51 --> msg52
  msg53["Looking for recommendations, if there is a place I..."]
  msg52 --> msg53
  msg54["What is the contract address of mPOOL? Verify plea..."]
  msg53 --> msg54
  msg55["I was unsure, because I had to add it manually to ..."]
  msg54 --> msg55
  msg56["But POOL showed up automatically under ETH Mainnet..."]
  msg55 --> msg56
  msg57["mPOOL isn't listed on CoinGecko..."]
  msg56 --> msg57
  msg58["should maybe change the name of mPOOL to matiPool ..."]
  msg57 --> msg58
  msg59["Still confusing, because it is what another coin (..."]
  msg58 --> msg59
  msg60["And the name here does not coincide: https://polyg..."]
  msg59 --> msg60
  msg61["Just looking out, trying to help......"]
  msg60 --> msg61
  msg62["So, when I DM Collab.Land; '!withdraw mPOOL', do I..."]
  msg61 --> msg62
  msg63["I missed this reply question, originally. Did you ..."]
  msg62 --> msg63
  subgraph "1/6/2022"
    msg64["⁠general⁠..."]
  end
  msg63 --> msg64
  msg65["⁠general⁠..."]
  msg64 --> msg65
  msg66["⁠general⁠..."]
  msg65 --> msg66
  msg67["And: ⁠general⁠..."]
  msg66 --> msg67
  msg68["gm..."]
  msg67 --> msg68
  msg69["So what does the future integration between Tribe ..."]
  msg68 --> msg69
  msg70["I just thought of a really cool way to potentially..."]
  msg69 --> msg70
  msg71["We could create a new pool that this is the only w..."]
  msg70 --> msg71
  msg72["⁠PT NFT brainstorm?⁠..."]
  msg71 --> msg72
  subgraph "1/7/2022"
    msg73["Love to see those creative juices flowing!..."]
  end
  msg72 --> msg73
  subgraph "1/8/2022"
    msg74["Just want to say, I love your bold creativity mang..."]
  end
  msg73 --> msg74
  msg75["I am not technically savvy enough to know if the t..."]
  msg74 --> msg75
  msg76["StarTreeTV🌊🏆
POOL Hodler
 — 
1/8/22, 10:04 PM
Sa..."]
  msg75 --> msg76
  msg77["StarTreeTV🌊🏆
POOL Hodler
 — 
1/8/22, 10:05 PM
Sa..."]
  msg76 --> msg77
  subgraph "1/10/2022"
    msg78["I am interested in hearing the details please. Fee..."]
  end
  msg77 --> msg78
  msg79["Was just reading through their white paper real qu..."]
  msg78 --> msg79
  msg80["How it would potentially work with PT, I'm not sur..."]
  msg79 --> msg80
  msg81["From what I gathered by reading, I'm not sure it w..."]
  msg80 --> msg81
  msg82["Can anyone explain to me (like I'm a 4yo), how the..."]
  msg81 --> msg82
  subgraph "1/11/2022"
    msg83["The NFTs can all be claimed on Polygon even if the..."]
  end
  msg82 --> msg83
  msg84["or AVAX..."]
  msg83 --> msg84
  msg85["Ah, ok thanks...."]
  msg84 --> msg85
  msg86["gm..."]
  msg85 --> msg86
  msg87["'Drop NFTs through PT'? Please explain what you me..."]
  msg86 --> msg87
  msg88["Like people would create their own individual pool..."]
  msg87 --> msg88
  msg89["What tokens would be distributed? Did you mean NTF..."]
  msg88 --> msg89
  msg90["Would these NFT projects need to be voted on by th..."]
  msg89 --> msg90
  msg91["Well see that was my concern...."]
  msg90 --> msg91
  msg92["In terms of adjusting prize distributions, you are..."]
  msg91 --> msg92
  subgraph "1/12/2022"
    msg93["So the NFTs get randomly distributed to the wallet..."]
  end
  msg92 --> msg93
  msg94["gm!..."]
  msg93 --> msg94
  msg95["Hey, I didn't know you knew my x!? ..."]
  msg94 --> msg95
  msg96["Sorry if I already asked this, but are you thinkin..."]
  msg95 --> msg96
  msg97["Is it possible to have a 2nd pool clone, and exact..."]
  msg96 --> msg97
  msg98["I should explain more of what I meant in the 2nd p..."]
  msg97 --> msg98
  msg99["Sorry to be cross posting from the ⁠PT NFT brainst..."]
  msg98 --> msg99
  msg100["@Thumbs Up Nice video! So, is that the preferable ..."]
  msg99 --> msg100
  msg101["Yeah I bought $USDC from Coinbase thinking there w..."]
  msg100 --> msg101
  msg102["Would be good to put together a chart that show fr..."]
  msg101 --> msg102
  msg103["Make an NFT outa that thing!..."]
  msg102 --> msg103
  msg104["Do you publish directly to Twitter? And just a hea..."]
  msg103 --> msg104
  msg105["From my laptop:..."]
  msg104 --> msg105
  msg106["Do you mean in my browser setting or something? I ..."]
  msg105 --> msg106
  msg107["Success!..."]
  msg106 --> msg107
  subgraph "1/13/2022"
    msg108["gm..."]
  end
  msg107 --> msg108
  msg109["Hey, let's create a #gm thread.?..."]
  msg108 --> msg109
  subgraph "1/14/2022"
    msg110["gm ..."]
  end
  msg109 --> msg110
  msg111["gm..."]
  msg110 --> msg111
  msg112["Just a little something..."]
  msg111 --> msg112
  msg113["Anyone known if there is such thing as a Discord b..."]
  msg112 --> msg113
  msg114["Can't wait to hear more updates about this!..."]
  msg113 --> msg114
  msg115["Thanks, I'll check these...."]
  msg114 --> msg115
  msg116["Super exciting! I am very interested in learning t..."]
  msg115 --> msg116
  msg117["Boom, this would work!..."]
  msg116 --> msg117
  msg118["I think PT should invest in this...."]
  msg117 --> msg118
  msg119["Do you have ideas of the tech that could currently..."]
  msg118 --> msg119
  msg120["Is 'multi-delegation' function something on the fo..."]
  msg119 --> msg120
  msg121["I was thinking, how about creating a new token POO..."]
  msg120 --> msg121
  msg122["That one change would facilitate a big wave of inn..."]
  msg121 --> msg122
  msg123["Yeah, I noticed that in some recent explainer vide..."]
  msg122 --> msg123
  msg124["I had an idea (hope it makes sense..). How to expl..."]
  msg123 --> msg124
  msg125["Why not tie POOL to TRIBE?..."]
  msg124 --> msg125
  msg126["Hmmm, I'm thinking it's not the same idea, but I w..."]
  msg125 --> msg126
  msg127["I wish I was knowledgeable enough to give you a co..."]
  msg126 --> msg127
  msg128["I'm honestly still not getting how the prizecap wo..."]
  msg127 --> msg128
  subgraph "1/16/2022"
    msg129["gm..."]
  end
  msg128 --> msg129
  msg130["@Leighton 🌊🏆 , I saw you're listed as an 'Adviso..."]
  msg129 --> msg130
  subgraph "1/17/2022"
    msg131["gm
https://tenor.com/view/tired-sleepy-tomand-jerr..."]
  end
  msg130 --> msg131
  msg132["Cool and Cool! gm ..."]
  msg131 --> msg132
  msg133["@Leighton 🌊🏆 , wasn't sure if you had seen my DM..."]
  msg132 --> msg133
  msg134["No worries, the DM system on Discord does not make..."]
  msg133 --> msg134
  msg135["I didn't see anywhere, where it said, '2/
 Change ..."]
  msg134 --> msg135
  msg136["Where is the Tweet link to RT?..."]
  msg135 --> msg136
  msg137["I think it should be optional if possible...."]
  msg136 --> msg137
  msg138["I like the idea that the POOL that one is going to..."]
  msg137 --> msg138
  subgraph "Invalid Date"
    msg139["Just chiming in to say, great ideas in the post an..."]
  end
  msg138 --> msg139
  subgraph "11/25/2021"
    msg140["A Happy Thanksgiving, to all that celebrate it! ..."]
  end
  msg139 --> msg140
  subgraph "11/26/2021"
    msg141["@Deleted User !trythev4..."]
  end
  msg140 --> msg141
  msg142["@POAP.love !trythev4..."]
  msg141 --> msg142
  msg143["!trythev4..."]
  msg142 --> msg143
  msg144["Hey Y'all Just sharing what seems like important i..."]
  msg143 --> msg144
  msg145["ps. the title is kinda clickbait..."]
  msg144 --> msg145
  subgraph "11/28/2021"
    msg146["I'd like to request some POOL tokens for the abili..."]
  end
  msg145 --> msg146
