import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { spawnSync } from 'node:child_process';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const packageRoot = path.resolve(__dirname, '..');
const pythonRoot = path.join(packageRoot, 'generated', 'python');
const contractsPyRoot = path.join(pythonRoot, 'tnf_contracts');
const jsonSchemaRoot = path.join(packageRoot, 'generated', 'jsonschema');

const pythonExe = process.env.PYTHON || process.env.PYTHON3 || 'python3';

const mappings = [
  {
    input: path.join(jsonSchemaRoot, 'twip', 'twip-identity.schema.json'),
    output: path.join(contractsPyRoot, 'twip_identity.py'),
  },
  {
    input: path.join(jsonSchemaRoot, 'twip', 'twip-envelope.schema.json'),
    output: path.join(contractsPyRoot, 'twip_envelope.py'),
  },
  {
    input: path.join(jsonSchemaRoot, 'sgp', 'sgp-payloads.schema.json'),
    output: path.join(contractsPyRoot, 'sgp_payloads.py'),
  },
  {
    input: path.join(jsonSchemaRoot, 'sgp', 'sgp-envelope.schema.json'),
    output: path.join(contractsPyRoot, 'sgp_envelope.py'),
  },
  {
    input: path.join(jsonSchemaRoot, 'adk', 'execute-request.schema.json'),
    output: path.join(contractsPyRoot, 'adk_execute_request.py'),
  },
  {
    input: path.join(jsonSchemaRoot, 'adk', 'execute-response.schema.json'),
    output: path.join(contractsPyRoot, 'adk_execute_response.py'),
  },
  {
    input: path.join(jsonSchemaRoot, 'scraping', 'scrape-request.schema.json'),
    output: path.join(contractsPyRoot, 'scrape_request.py'),
  },
  {
    input: path.join(jsonSchemaRoot, 'scraping', 'scrape-response.schema.json'),
    output: path.join(contractsPyRoot, 'scrape_response.py'),
  },
  {
    input: path.join(jsonSchemaRoot, 'crypto', 'crypto.schema.json'),
    output: path.join(contractsPyRoot, 'crypto_operations.py'),
  },
  {
    input: path.join(jsonSchemaRoot, 'messaging', 'envelope.schema.json'),
    output: path.join(contractsPyRoot, 'messaging.py'),
  },
];

function runPython(args) {
  const result = spawnSync(pythonExe, args, {
    cwd: packageRoot,
    stdio: 'pipe',
    encoding: 'utf8',
  });

  if (result.status !== 0) {
    const stderr = result.stderr?.trim() || result.stdout?.trim() || 'unknown error';
    throw new Error(stderr);
  }
}

async function writePythonModule(targetPath, contents) {
  await mkdir(path.dirname(targetPath), { recursive: true });
  await writeFile(targetPath, contents, 'utf8');
}

async function writePythonPackageModules() {
  const initPy = `# Auto-generated by packages/protocol-contracts/scripts/generate-python.mjs\n\nfrom .adk_execute_request import ExecuteRequest\nfrom .adk_execute_response import ExecuteResponse\nfrom .scrape_request import ScrapeRequest\nfrom .scrape_response import ScrapeResponse\n\n__all__ = [\n    \"ExecuteRequest\",\n    \"ExecuteResponse\",\n    \"ScrapeRequest\",\n    \"ScrapeResponse\",\n]\n`;

  await writePythonModule(path.join(contractsPyRoot, '__init__.py'), initPy);
}

async function main() {
  runPython(['-m', 'datamodel_code_generator', '--version']);

  for (const mapping of mappings) {
    await mkdir(path.dirname(mapping.output), { recursive: true });

    const args = [
      '-m',
      'datamodel_code_generator',
      '--input',
      mapping.input,
      '--input-file-type',
      'jsonschema',
      '--output',
      mapping.output,
      '--output-model-type',
      'pydantic_v2.BaseModel',
      '--target-python-version',
      '3.11',
      '--use-standard-collections',
      '--use-schema-description',
      '--disable-timestamp',
      '--field-constraints',
    ];

    runPython(args);
    console.log(`[protocol-contracts] wrote ${path.relative(packageRoot, mapping.output)}`);
  }

  await writePythonPackageModules();
}

main().catch((error) => {
  if (/No module named datamodel_code_generator/.test(error.message)) {
    console.error(
      '[protocol-contracts] datamodel-code-generator is required. Install with: python3 -m pip install datamodel-code-generator',
    );
  } else {
    console.error(`[protocol-contracts] Python model generation failed: ${error.message}`);
  }
  process.exit(1);
});
