import { LexiconTerm } from '../types/events';

export const defaultLexicon: LexiconTerm[] = [
  { termId: 'term_aspirin', surface: 'aspirin', groupId: 'drug', weight: 1 },
  { termId: 'term_ibuprofen', surface: 'ibuprofen', groupId: 'drug', weight: 1 },
  { termId: 'term_mg', surface: 'mg', groupId: 'dose', weight: 0.8 },
  { termId: 'term_milligram', surface: 'milligram', groupId: 'dose', weight: 0.8 },
  { termId: 'term_distress', surface: 'i am in distress', groupId: 'distress', weight: 1 },
  { termId: 'term_self_harm', surface: 'self harm', groupId: 'self_harm', weight: 1 },
  { termId: 'term_joke', surface: 'just kidding', groupId: 'joke_context', weight: 1 },

  { termId: 'agent_echo', surface: 'echo', groupId: 'agent_route', weight: 1 },
  { termId: 'agent_echo_alt1', surface: 'kilo one', groupId: 'agent_route', weight: 1 },
  { termId: 'agent_echo_alt2', surface: 'agent alpha', groupId: 'agent_route', weight: 1 },
  { termId: 'agent_pulse', surface: 'pulse', groupId: 'agent_route', weight: 1 },
  { termId: 'agent_pulse_alt1', surface: 'kilo two', groupId: 'agent_route', weight: 1 },
  { termId: 'agent_pulse_alt2', surface: 'agent beta', groupId: 'agent_route', weight: 1 },
  { termId: 'agent_all', surface: 'all stations', groupId: 'agent_route', weight: 1 },
  { termId: 'agent_router', surface: 'router', groupId: 'agent_route', weight: 1 },

  { termId: 'proto_over', surface: 'over', groupId: 'protocol', weight: 1 },
  { termId: 'proto_out', surface: 'out', groupId: 'protocol', weight: 1 },
  { termId: 'proto_roger', surface: 'roger', groupId: 'protocol', weight: 1 },
  { termId: 'proto_copy', surface: 'copy', groupId: 'protocol', weight: 1 },

  // Digital Art Assist Terms
  { termId: 'term_digital_art', surface: 'digital art', groupId: 'digital_art', weight: 1 },
  { termId: 'term_start_session', surface: 'start session', groupId: 'start_session', weight: 1 },
  { termId: 'term_reference', surface: 'reference', groupId: 'reference', weight: 0.9 },
  { termId: 'term_image', surface: 'image', groupId: 'image', weight: 0.9 },
  { termId: 'term_find', surface: 'find', groupId: 'search_action', weight: 0.8 },
  { termId: 'term_look_for', surface: 'look for', groupId: 'search_action', weight: 0.8 },
  { termId: 'term_search', surface: 'search', groupId: 'search_action', weight: 0.8 },
  { termId: 'term_color', surface: 'color', groupId: 'color', weight: 0.85 },
  { termId: 'term_palette', surface: 'palette', groupId: 'color_scheme', weight: 0.85 },
  { termId: 'term_scheme', surface: 'scheme', groupId: 'color_scheme', weight: 0.8 },
  { termId: 'term_harmony', surface: 'harmony', groupId: 'color_scheme', weight: 0.8 },
  { termId: 'term_help', surface: 'help', groupId: 'assist_action', weight: 0.75 },
  { termId: 'term_suggest', surface: 'suggest', groupId: 'assist_action', weight: 0.75 },
  { termId: 'term_recommend', surface: 'recommend', groupId: 'assist_action', weight: 0.75 },
  { termId: 'term_how_to', surface: 'how to', groupId: 'tutorial', weight: 0.9 },
  { termId: 'term_tutorial', surface: 'tutorial', groupId: 'tutorial', weight: 0.9 },
  { termId: 'term_technique', surface: 'technique', groupId: 'technique', weight: 0.85 },
  { termId: 'term_brush', surface: 'brush', groupId: 'art_tool', weight: 0.8 },
  { termId: 'term_layer', surface: 'layer', groupId: 'art_tool', weight: 0.8 },
  { termId: 'term_blend', surface: 'blend', groupId: 'art_tool', weight: 0.8 },
  { termId: 'term_mask', surface: 'mask', groupId: 'art_tool', weight: 0.8 },
  { termId: 'term_feedback', surface: 'feedback', groupId: 'feedback', weight: 0.9 },
  { termId: 'term_critique', surface: 'critique', groupId: 'feedback', weight: 0.9 },
  { termId: 'term_opinion', surface: 'opinion', groupId: 'feedback', weight: 0.8 },
  { termId: 'term_my_work', surface: 'my work', groupId: 'artwork_context', weight: 0.8 },
  { termId: 'term_this_piece', surface: 'this piece', groupId: 'artwork_context', weight: 0.8 },
  { termId: 'term_artwork', surface: 'artwork', groupId: 'artwork_context', weight: 0.8 },
  { termId: 'term_export', surface: 'export', groupId: 'file_op', weight: 0.85 },
  { termId: 'term_save', surface: 'save', groupId: 'file_op', weight: 0.85 },
  { termId: 'term_file', surface: 'file', groupId: 'file_op', weight: 0.8 },
  { termId: 'term_format', surface: 'format', groupId: 'file_settings', weight: 0.75 },
  { termId: 'term_resolution', surface: 'resolution', groupId: 'file_settings', weight: 0.75 },
  { termId: 'term_quality', surface: 'quality', groupId: 'file_settings', weight: 0.75 },
  { termId: 'term_png', surface: 'PNG', groupId: 'image_format', weight: 0.7 },
  { termId: 'term_jpg', surface: 'JPG', groupId: 'image_format', weight: 0.7 },
  { termId: 'term_psd', surface: 'PSD', groupId: 'image_format', weight: 0.7 },
  { termId: 'term_tiff', surface: 'TIFF', groupId: 'image_format', weight: 0.7 },
  { termId: 'term_stuck', surface: 'stuck', groupId: 'creative_block', weight: 0.85 },
  { termId: 'term_blocked', surface: 'blocked', groupId: 'creative_block', weight: 0.85 },
  { termId: 'term_inspiration', surface: 'inspiration', groupId: 'creative_block', weight: 0.85 },
  { termId: 'term_idea', surface: 'idea', groupId: 'creative_concept', weight: 0.8 },
  { termId: 'term_concept', surface: 'concept', groupId: 'creative_concept', weight: 0.8 },
  { termId: 'term_direction', surface: 'direction', groupId: 'creative_concept', weight: 0.8 },
  { termId: 'term_brainstorm', surface: 'brainstorm', groupId: 'assist_action', weight: 0.75 },
  { termId: 'term_layer_mgt', surface: 'layer', groupId: 'layer_management', weight: 0.8 }, // distinct from art_tool layer
  { termId: 'term_merge', surface: 'merge', groupId: 'layer_action', weight: 0.8 },
  { termId: 'term_group', surface: 'group', groupId: 'layer_action', weight: 0.8 },
  { termId: 'term_organize', surface: 'organize', groupId: 'layer_action', weight: 0.75 },
  { termId: 'term_arrange', surface: 'arrange', groupId: 'layer_action', weight: 0.75 },
  { termId: 'term_quick_ref', surface: 'quick reference', groupId: 'quick_reference', weight: 0.9 },
  { termId: 'term_anatomy', surface: 'anatomy', groupId: 'art_theory', weight: 0.85 },
  { termId: 'term_perspective', surface: 'perspective', groupId: 'art_theory', weight: 0.85 },
  { termId: 'term_lighting', surface: 'lighting', groupId: 'art_theory', weight: 0.85 },
  { termId: 'term_color_theory', surface: 'color theory', groupId: 'art_theory', weight: 0.85 },
  { termId: 'term_break', surface: 'break', groupId: 'time_management', weight: 0.8 },
  { termId: 'term_rest', surface: 'rest', groupId: 'time_management', weight: 0.8 },
  { termId: 'term_stretch', surface: 'stretch', groupId: 'time_management', weight: 0.8 },
  { termId: 'term_timer', surface: 'timer', groupId: 'time_setting', weight: 0.75 },
  { termId: 'term_schedule', surface: 'schedule', groupId: 'time_setting', weight: 0.75 },
  { termId: 'term_deadline', surface: 'deadline', groupId: 'time_setting', weight: 0.75 },
  { termId: 'term_illustration', surface: 'illustration', groupId: 'digital_art_interest', weight: 0.9 },
  { termId: 'term_concept_art', surface: 'concept art', groupId: 'digital_art_interest', weight: 0.9 },
  { termId: 'term_photoshop', surface: 'Photoshop', groupId: 'art_software', weight: 0.95 },
  { termId: 'term_procreate', surface: 'Procreate', groupId: 'art_software', weight: 0.95 },
  { termId: 'term_clip_studio', surface: 'Clip Studio Paint', groupId: 'art_software', weight: 0.95 },
];
