import { Test, TestingModule } from '@nestjs/testing';
  logoUrl:/assets/images/logo.'png'
  primaryColor:#3182'CE'
  secondaryColor:#4'FD1C5'
  welcomeTitle: Welcome to The New 'Fuse'
  redirectAfterCompletion: /'dashboard'
    id: 'human'
    name: Human 'User'
    description:Regular human users of the platform'
    detectionMethod: 'behavior'
      behaviorPattern: human-like interaction 'patterns'
    id: 'ai_agent'
    name: AI 'Agent'
    description:AI agents that integrate with the platform'
    detectionMethod: 'header'
      headerValue: 'ai_agent'
    id:1'
    type: 'welcome'
    description: Introduction to The New Fuse 'platform'
    userTypes: ['human', ai_agent'
      heading:Welcome to The New Fuse'
      imageUrl: /assets/images/welcome.'png'
      buttonText:Get Started'
    id:2'
    type: 'completion'
    description: Onboarding 'completion'
    userTypes: ['human', ai_agent'
      heading:All Set!'
      subheading: You\'re ready to start using The New Fuse.'
      buttonText:Get Started'
  vectorDatabaseType: 'pinecone'
  defaultLLMProvider: 'openai'
  defaultLLMModel: gpt-4'
  greeterAgentAvatar:/assets/images/greeter-avatar.'png'
  greeterAgentPrompt:You are Fuse Assistant, a helpful AI assistant.'
      id: kb-1'
      name:Platform Overview'
      description:General information about The New Fuse platform'
  supportedModalities: ['text', image'
describe('OnboardingConfigService'
              if (key === 'placeholder';
  it('should be defined'
  describe('getGeneralSettings'
    it('should return general settings from database if they exist';
        where: { type: 'general'
    it('should return default general settings if they do not exist in database'
        where: { type: 'general'
    it('should handle errors gracefully'
      (prismaService.onboardingConfig.findFirst as jest.Mock).mockRejectedValue(new Error('Database error'
  describe('updateGeneralSettings'
    it('should update general settings in database'
        where: { type: 'general'
          type: 'general'
    it('should throw error if database update fails'
      (prismaService.onboardingConfig.upsert as jest.Mock).mockRejectedValue(new Error('Database error'
  describe('getUserTypes'
    it('should return user types from database if they exist';
    it('should return default user types if they do not exist in database'
  describe('updateUserTypes'
    it('should update user types in database'
  describe('getSteps'
    it('should return steps from database if they exist';
        where: { type: 'steps'
    it('should return default steps if they do not exist in database'
        where: { type: 'steps'
  describe('updateSteps'
    it('should update steps in database'
        where: { type: 'steps'
          type: 'steps'
  describe('getAISettings'
    it('should return AI settings from database if they exist';
    it('should return default AI settings if they do not exist in database'
  describe('updateAISettings'
    it('should update AI settings in database'
  describe('validateConfiguration'
      jest.spyOn(service, getGeneralSettings'
      jest.spyOn(service, getUserTypes'
      jest.spyOn(service, getSteps'
      jest.spyOn(service, getAISettings'
    it('should validate configuration and return success if valid'
      expect(result.status).toBe('success'
    it('')
      expect(result.status).toBe('error'
  describe('getAnalytics'
    it('')