import { OnModuleInit, OnModuleDestroy } from '@nestjs/common';
import { RedisConfig } from './RedisConfig';
import { QueueTask, SearchResult, CacheOptions, PubSubMessage, RedisHealth, RedisMetrics, RedisOperationLog } from './types';
export declare class UnifiedRedisService implements OnModuleInit, OnModuleDestroy {
    private readonly redisConfig;
    private readonly logger;
    private mainClient;
    private pubSubClient;
    private subscribers;
    private patternSubscribers;
    private metrics;
    private operationLogs;
    private readonly MAX_LOG_SIZE;
    constructor(redisConfig: RedisConfig);
    onModuleInit(): Promise<void>;
    onModuleDestroy(): Promise<void>;
    private initializeConnections;
    private setupEventHandlers;
    private executeOperation;
    private logOperation;
    private updateMetrics;
    get(key: string): Promise<string | null>;
    set(key: string, value: string, ttl?: number): Promise<void>;
    del(key: string): Promise<number>;
    exists(key: string): Promise<boolean>;
    expire(key: string, ttl: number): Promise<boolean>;
    hset(key: string, field: string, value: string): Promise<void>;
    hset(key: string, data: Record<string, string>): Promise<void>;
    hget(key: string, field: string): Promise<string | null>;
    hgetall(key: string): Promise<Record<string, string>>;
    hdel(key: string, field: string): Promise<number>;
    lpush(key: string, ...values: string[]): Promise<number>;
    rpop(key: string): Promise<string | null>;
    llen(key: string): Promise<number>;
    lrange(key: string, start: number, stop: number): Promise<string[]>;
    zadd(key: string, score: number, member: string): Promise<number>;
    zpopmax(key: string): Promise<string[]>;
    zrange(key: string, start: number, stop: number): Promise<string[]>;
    zrem(key: string, member: string): Promise<number>;
    sadd(key: string, ...members: string[]): Promise<number>;
    srem(key: string, ...members: string[]): Promise<number>;
    smembers(key: string): Promise<string[]>;
    sismember(key: string, member: string): Promise<boolean>;
    ltrim(key: string, start: number, stop: number): Promise<void>;
    lindex(key: string, index: number): Promise<string | null>;
    publish(channel: string, message: string | object): Promise<number>;
    subscribe(channel: string, callback: (message: PubSubMessage) => void): Promise<void>;
    psubscribe(pattern: string, callback: (message: PubSubMessage) => void): Promise<void>;
    unsubscribe(channel: string): Promise<void>;
    punsubscribe(pattern: string): Promise<void>;
    getAll(pattern: string): Promise<string[]>;
    setWorkflowState(workflowId: string, state: any): Promise<void>;
    getWorkflowState<T = any>(workflowId: string): Promise<T | null>;
    enqueue<T>(queueName: string, task: QueueTask<T>, priority?: number): Promise<void>;
    dequeue<T>(queueName: string): Promise<QueueTask<T> | null>;
    requeueWithBackoff<T>(queueName: string, task: QueueTask<T>, retryPenalty?: number): Promise<void>;
    vectorSet(key: string, vector: number[], metadata?: Record<string, any>): Promise<void>;
    vectorGet(key: string): Promise<{
        vector: number[];
        metadata?: Record<string, any>;
    } | null>;
    vectorSearch(searchVector: number[], limit?: number): Promise<SearchResult[]>;
    private calculateCosineSimilarity;
    cache<T>(key: string, factory: () => Promise<T>, options?: CacheOptions): Promise<T>;
    invalidateByTag(tag: string): Promise<void>;
    ping(): Promise<string>;
    flushdb(): Promise<void>;
    keys(pattern: string): Promise<string[]>;
    getHealth(): Promise<RedisHealth>;
    getMetrics(): RedisMetrics;
    getOperationLogs(limit?: number): RedisOperationLog[];
    private closeAllConnections;
}
//# sourceMappingURL=UnifiedRedisService.d.ts.map