[build]
builder = "DOCKERFILE"
dockerfilePath = "packages/core-vector-db/Dockerfile"
watchPaths = ["packages/core-vector-db/**", "packages/types/**", "packages/core/**"]

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyMaxRetries = 10
restartPolicyType = "ON_FAILURE"