[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"
watchPaths = ["./**", "../types/**", "../core/**", "../database/**"]

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyMaxRetries = 10
restartPolicyType = "ON_FAILURE"