import * as React from "react";
declare const DropdownMenu: any;
declare const DropdownMenuTrigger: any;
declare const DropdownMenuGroup: any;
declare const DropdownMenuPortal: any;
declare const DropdownMenuSub: any;
declare const DropdownMenuRadioGroup: any;
declare const DropdownMenuSubTrigger: React.ForwardRefExoticComponent<React.RefAttributes<unknown>>;
declare const DropdownMenuSubContent: React.ForwardRefExoticComponent<React.RefAttributes<unknown>>;
declare const DropdownMenuContent: React.ForwardRefExoticComponent<React.RefAttributes<unknown>>;
declare const DropdownMenuItem: React.ForwardRefExoticComponent<React.RefAttributes<unknown>>;
declare const DropdownMenuCheckboxItem: React.ForwardRefExoticComponent<React.RefAttributes<unknown>>;
declare const DropdownMenuRadioItem: React.ForwardRefExoticComponent<React.RefAttributes<unknown>>;
declare const DropdownMenuLabel: React.ForwardRefExoticComponent<React.RefAttributes<unknown>>;
declare const DropdownMenuSeparator: React.ForwardRefExoticComponent<React.RefAttributes<unknown>>;
declare const DropdownMenuShortcut: {
    (_a: any): import("react/jsx-runtime").JSX.Element;
    displayName: string;
};
export { DropdownMenu, DropdownMenuTrigger, DropdownMenuContent, DropdownMenuItem, DropdownMenuCheckboxItem, DropdownMenuRadioItem, DropdownMenuLabel, DropdownMenuSeparator, DropdownMenuShortcut, DropdownMenuGroup, DropdownMenuPortal, DropdownMenuSub, DropdownMenuSubContent, DropdownMenuSubTrigger, DropdownMenuRadioGroup, };
