FROM node:20-bullseye AS builder

WORKDIR /app

# Setup yarn
RUN corepack enable && \
    yarn set version berry && \
    yarn config set nodeLinker node-modules

COPY package.json yarn.lock ./
COPY packages ./packages
COPY apps ./apps

RUN yarn install
RUN yarn build

# Production image
FROM nginx:alpine

COPY --from=builder /app/dist /usr/share/nginx/html
COPY docker/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]