import React from 'react';
export declare const LazyWorkflowCanvas: React.LazyExoticComponent<any>;
export declare const LazyNodeToolbox: React.LazyExoticComponent<any>;
export declare const LazyNodeProperties: React.LazyExoticComponent<any>;
export declare const LazyWorkflowExecutionContext: React.LazyExoticComponent<any>;
export declare const LazyWorkflowDebugger: React.LazyExoticComponent<any>;
export declare const LazyWorkflowAnalytics: React.LazyExoticComponent<any>;
export declare const LazyWorkflowTemplates: React.LazyExoticComponent<any>;
export declare const LazyAgentNode: React.LazyExoticComponent<any>;
export declare const LazyA2ANode: React.LazyExoticComponent<any>;
export declare const LazyMCPToolNode: React.LazyExoticComponent<any>;
export declare const LazyTransformNode: React.LazyExoticComponent<any>;
export declare const LazyConditionNode: React.LazyExoticComponent<any>;
export declare const LazyNotificationNode: React.LazyExoticComponent<any>;
export declare const LazyInputNode: React.LazyExoticComponent<any>;
export declare const LazyOutputNode: React.LazyExoticComponent<any>;
export declare const WorkflowCanvas: (props: any) => import("react/jsx-runtime").JSX.Element;
export declare const NodeToolbox: (props: any) => import("react/jsx-runtime").JSX.Element;
export declare const NodeProperties: (props: any) => import("react/jsx-runtime").JSX.Element;
export declare const WorkflowExecutionContext: (props: any) => import("react/jsx-runtime").JSX.Element;
export declare const WorkflowDebugger: (props: any) => import("react/jsx-runtime").JSX.Element;
export declare const WorkflowAnalytics: (props: any) => import("react/jsx-runtime").JSX.Element;
export declare const WorkflowTemplates: (props: any) => import("react/jsx-runtime").JSX.Element;
export declare const AgentNode: (props: any) => import("react/jsx-runtime").JSX.Element;
export declare const A2ANode: (props: any) => import("react/jsx-runtime").JSX.Element;
export declare const MCPToolNode: (props: any) => import("react/jsx-runtime").JSX.Element;
export declare const TransformNode: (props: any) => import("react/jsx-runtime").JSX.Element;
export declare const ConditionNode: (props: any) => import("react/jsx-runtime").JSX.Element;
export declare const NotificationNode: (props: any) => import("react/jsx-runtime").JSX.Element;
export declare const InputNode: (props: any) => import("react/jsx-runtime").JSX.Element;
export declare const OutputNode: (props: any) => import("react/jsx-runtime").JSX.Element;
