export interface LegacyRedirect {
  from: string;
  to: string;
}

// Compatibility redirects to preserve legacy entry points while consolidating IA.
export const LEGACY_REDIRECTS: LegacyRedirect[] = [
  // OpenClaw-style operational aliases
  { from: '/overview', to: '/dashboard' },
  { from: '/channels', to: '/command-center' },
  { from: '/instances', to: '/observatory' },
  { from: '/sessions', to: '/multi-agent-chat' },
  { from: '/usage', to: '/analytics' },
  { from: '/cron-jobs', to: '/tasks' },
  { from: '/skills', to: '/resources' },
  { from: '/nodes', to: '/observatory' },
  { from: '/config', to: '/settings' },
  { from: '/logs', to: '/admin/audit-logs' },
  { from: '/audit-logs', to: '/admin/audit-logs' },
  { from: '/tnf-hub', to: '/hub' },

  { from: '/admin/panel', to: '/admin' },
  { from: '/team', to: '/workspace/members' },
  { from: '/workspace', to: '/workspace/overview' },
  { from: '/agents/unified-creator', to: '/agents/new' },
  { from: '/workspace/chat', to: '/workspace-chat' },
  { from: '/workspace/layout', to: '/workspace/overview' },
  { from: '/login', to: '/auth/login' },
  { from: '/register', to: '/auth/register' },
  { from: '/auth/google/callback', to: '/auth/google-callback' },
  { from: '/auth/callback', to: '/auth/oauth-callback' },
  { from: '/integrations', to: '/connect' },
  { from: '/ide', to: '/command-center' },
  { from: '/privacy', to: '/legal/privacy' },
  { from: '/terms', to: '/legal/terms' },
  { from: '/forgot-password', to: '/auth/forgot-password' },
  { from: '/api/docs', to: '/docs' },
  { from: '/help/documentation', to: '/docs' },
  { from: '/help/tutorials', to: '/docs' },
  { from: '/help/faq', to: '/docs' },
  { from: '/help/support', to: '/support' },
  { from: '/help/community', to: '/community' },
  { from: '/landing-page', to: '/landing' },
  { from: '/simple-landing', to: '/landing' },
  { from: '/components-nav', to: '/components' },
  { from: '/tasks-page', to: '/tasks' },
  { from: '/chat-page', to: '/chat' },
  { from: '/workflows/detail', to: '/workflows' },
  { from: '/workflows/execution', to: '/workflows/executions' },
  { from: '/admin/dashboard', to: '/admin' },
  { from: '/admin/experimental-features', to: '/admin/feature-flags' },
  { from: '/admin/onboarding', to: '/admin' },
  { from: '/general-settings/community-hub', to: '/general-settings' },
  { from: '/api/admin/features/:id/evaluate', to: '/api/admin/features' },
];
