import { Injectable, Logger } from '@nestjs/common';
import { UnifiedRedisService } from '@the-new-fuse/infrastructure';
import { createHmac } from 'crypto';

/**
 * TNF Federated Identity Service
 *
 * Implements "ID# Encoding" and cryptographic attribution for the
 * Software 3.0 Agent Federation.
 */

// -----------------------------------------------------------------------------
// Canonical Federated Base58 alphabet and encoder (Phase 9 / FOLLOWUP-2).
//
// These are exported at module level so callers outside the NestJS DI
// container (the registry-bridge, the seeder, transcript processors) can
// re-use the exact same encoding. If you change FEDERATED_BASE58_ALPHABET,
// update every sibling mirror (e.g. TranscriptProcessorV2 FEDERATED_BASE58_ALPHABET,
// seed-agent-registry FEDERATED_BASE58_ALPHABET) in lock-step.
// -----------------------------------------------------------------------------
export const FEDERATED_BASE58_ALPHABET =
  '123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz';

export function encodeFederatedBase58(num: number): string {
  if (!Number.isFinite(num) || num <= 0) return FEDERATED_BASE58_ALPHABET[0];
  let remaining = Math.trunc(num);
  let encoded = '';
  while (remaining > 0) {
    encoded = FEDERATED_BASE58_ALPHABET[remaining % 58] + encoded;
    remaining = Math.floor(remaining / 58);
  }
  return encoded;
}

@Injectable()
export class FederatedIdentityService {
  private readonly logger = new Logger(FederatedIdentityService.name);

  constructor(private readonly redisService: UnifiedRedisService) {}

  /**
   * Encodes a sequential ID into a compact, secure ID# string.
   * Format: ID#:<encoded_id>
   *
   * If `agentId` already has an `id_number` registered (e.g. from the
   * seeder or a prior assignment), returns that value unchanged instead
   * of allocating a new sequence. This makes the round-trip to
   * agents.id_number idempotent across process restarts.
   */
  async generateIdNumber(agentId: string, knownIdNumber?: string | null): Promise<string> {
    if (knownIdNumber && /^ID#:[1-9A-HJ-NP-Za-km-z]+$/.test(knownIdNumber)) {
      return knownIdNumber;
    }
    const key = `tnf:identity:seq:${agentId}`;
    // Using increment to get a sequential number per agent
    const seq = await this.redisService.incr(key);

    // Encode using Base58 for compactness and visual distinction
    const encoded = encodeFederatedBase58(seq);
    const idNumber = `ID#:${encoded}`;

    this.logger.debug(`Generated identity for ${agentId}: ${idNumber} (seq: ${seq})`);
    return idNumber;
  }

  /**
   * Returns the next-sequence integer for an agent WITHOUT bumping the counter.
   * Used for observability/diff, not for actual allocation. Returns null if
   * agent has never been sequenced.
   */
  async peekSequence(agentId: string): Promise<number | null> {
    try {
      const v = await this.redisService.get(`tnf:identity:seq:${agentId}`);
      if (v == null) return null;
      const n = typeof v === 'number' ? v : typeof v === 'string' ? parseInt(v, 10) : NaN;
      return Number.isFinite(n) ? n : null;
    } catch {
      return null;
    }
  }

  /**
   * Verifies the cryptographic attribution of an AI Wiki entry.
   * Ensures the entry was generated by the agent it claims.
   */
  verifyAttribution(
    agentId: string,
    idNumber: string,
    content: string,
    signature: string,
    secret: string
  ): boolean {
    const message = `${agentId}|${idNumber}|${createHmac('sha256', secret).update(content).digest('hex')}`;
    const expectedSignature = createHmac('sha256', secret).update(message).digest('hex');

    const isValid = signature === expectedSignature;
    if (!isValid) {
      this.logger.warn(`Attribution failure for ${agentId} (${idNumber})`);
    }
    return isValid;
  }
}
