import { UnifiedWorkflow, WorkflowNode, WorkflowNodeType, WorkflowConnection } from '../types/WorkflowTypes';

/**
 * Enhanced Cloudflare Workflow Transpiler
 *
 * Transpiles TNF's visual ReactFlow JSON schema into an executable
 * Cloudflare Workers Workflow (AST-compatible JS/TS class).
 * Supports complex branching (conditions) and parallel execution.
 */
export class CloudflareWorkflowTranspiler {
  /**
   * Transpile a TNF UnifiedWorkflow into a Cloudflare Workflow Entrypoint.
   */
  public transpile(workflow: UnifiedWorkflow): string {
    const className = this.sanitizeClassName(workflow.name);
    const startNode = workflow.definition.nodes.find(n => n.type === WorkflowNodeType.START);
    
    if (!startNode) {
      throw new Error('Workflow must have a START node');
    }

    // Use a recursive generator to handle branches and nesting
    const runBody = this.generateNodeChain(startNode, workflow, new Set());

    return `
import { WorkflowEntrypoint, WorkflowStep, WorkflowEvent } from 'cloudflare:workers';

type Env = {
  TNF_API_URL: string;
  TNF_API_KEY?: string;
};

/**
 * ${workflow.name}
 * Auto-generated by TNF Transpiler
 */
export class ${className} extends WorkflowEntrypoint<Env, any> {
  async run(event: WorkflowEvent<any>, step: WorkflowStep) {
    const env = this.env;
    let context = event.payload || {};

${runBody}
    
    return { status: "completed", finalContext: context };
  }
}
`.trim();
  }

  /**
   * Recursively generate code for a chain of nodes.
   */
  private generateNodeChain(
    currentNode: WorkflowNode, 
    workflow: UnifiedWorkflow, 
    visited: Set<string>
  ): string {
    if (visited.has(currentNode.id)) return '    // Circular reference detected or path merged\n';
    visited.add(currentNode.id);

    let code = '';

    // 1. Generate code for current node
    if (currentNode.type !== WorkflowNodeType.START && currentNode.type !== WorkflowNodeType.END) {
      code += this.transpileNode(currentNode);
    }

    // 2. Determine next steps
    const outgoingConnections = workflow.definition.connections.filter(c => c.sourceNodeId === currentNode.id);

    if (currentNode.type === WorkflowNodeType.CONDITION) {
      const trueEdge = outgoingConnections.find(c => c.sourceHandle === 'true' || c.sourceHandle === 'output');
      const falseEdge = outgoingConnections.find(c => c.sourceHandle === 'false');
      
      const config = (currentNode.config as any) || {};
      const expression = config.expression || 'true';

      code += `
    if (${expression}) {
${trueEdge ? this.generateNodeChain(this.findNode(trueEdge.targetNodeId, workflow), workflow, new Set(visited)) : '      // No true path'}
    } else {
${falseEdge ? this.generateNodeChain(this.findNode(falseEdge.targetNodeId, workflow), workflow, new Set(visited)) : '      // No false path'}
    }
`;
      return code;
    }

    if (currentNode.type === WorkflowNodeType.PARALLEL) {
      const parallelBranches = outgoingConnections.map(c => 
        this.generateNodeChain(this.findNode(c.targetNodeId, workflow), workflow, new Set(visited))
      );

      code += `
    // Parallel Execution
    await Promise.all([
${parallelBranches.map(branch => `      (async () => {\n${branch}\n      })()`).join(',\n')}
    ]);
`;
      return code;
    }

    // Default linear flow
    if (outgoingConnections.length > 0) {
      const nextNode = this.findNode(outgoingConnections[0].targetNodeId, workflow);
      code += this.generateNodeChain(nextNode, workflow, visited);
    }

    return code;
  }

  private transpileNode(node: WorkflowNode): string {
    const config = (node.config as any) || {};
    const stepName = config.stepName || this.sanitizeStepName(node.name);

    switch (node.type) {
      case WorkflowNodeType.CLOUDFLARE_STEP_DO:
        const retries = config.retries ? `, { retries: { limit: ${config.retries}, delay: "5 seconds" } }` : '';
        return `
    context.${stepName} = await step.do("${stepName}"${retries}, async () => {
      console.log("Executing ${stepName}");
      return { success: true, timestamp: new Date().toISOString() };
    });
`;

      case WorkflowNodeType.CLOUDFLARE_STEP_SLEEP:
        const duration = config.sleepDuration || 1000;
        return `    await step.sleep("${stepName}", "${duration} milliseconds");\n`;

      case WorkflowNodeType.AGENT_TASK:
        return `
    context.${stepName} = await step.do("${stepName}", { retries: { limit: 3, delay: "10s" } }, async () => {
      const res = await fetch(env.TNF_API_URL + '/api/agent/trigger', {
         method: 'POST',
         headers: { 'Content-Type': 'application/json', 'Authorization': \`Bearer \${env.TNF_API_KEY || ''}\` },
         body: JSON.stringify({ 
           task: "${config.task || ''}",
           agentType: "${config.agentType || ''}",
           context: context
         })
      });
      if (!res.ok) throw new Error(\`TNF Agent trigger failed: \${res.status}\`);
      return await res.json();
    });
`;

      default:
        return `    // Node: ${node.name} (${node.type})\n`;
    }
  }

  private findNode(id: string, workflow: UnifiedWorkflow): WorkflowNode {
    const node = workflow.definition.nodes.find(n => n.id === id);
    if (!node) throw new Error(`Node not found: ${id}`);
    return node;
  }

  private sanitizeClassName(name: string): string {
    return name.replace(/[^a-zA-Z0-9]/g, '') || 'TnfWorkflow';
  }

  private sanitizeStepName(name: string): string {
    return name.replace(/[^a-zA-Z0-9_]/g, '_').toLowerCase() || 'step';
  }
}
