import { UnifiedWorkflow, WorkflowNode, WorkflowNodeType } from '../types/WorkflowTypes.js';

/**
 * Enhanced Cloudflare Workflow Transpiler
 *
 * Transpiles TNF's visual ReactFlow JSON schema into an executable
 * Cloudflare Workers Workflow (AST-compatible JS/TS class).
 * Supports complex branching (conditions) and parallel execution.
 */
export class CloudflareWorkflowTranspiler {
  /**
   * Transpile a TNF UnifiedWorkflow into a Cloudflare Workflow Entrypoint.
   */
  public transpile(workflow: UnifiedWorkflow): string {
    const className = this.sanitizeClassName(workflow.name);

    // Support both 'START' enum and 'input' type from frontend
    const startNode = workflow.definition.nodes.find(
      (n) => n.type === WorkflowNodeType.START || n.type === WorkflowNodeType.INPUT
    );

    if (!startNode) {
      throw new Error('Workflow must have a START or INPUT node');
    }

    // Use a recursive generator to handle branches and nesting
    const runBody = this.generateNodeChain(startNode, workflow, new Set());

    return `
import { WorkflowEntrypoint, WorkflowStep, WorkflowEvent } from 'cloudflare:workers';

type Env = {
  TNF_API_URL: string;
  TNF_API_KEY?: string;
};

/**
 * ${workflow.name}
 * Auto-generated by TNF Transpiler v2.0
 */
export class ${className} extends WorkflowEntrypoint<Env, any> {
  async run(event: WorkflowEvent<any>, step: WorkflowStep) {
    const env = this.env;
    let context = event.payload || {};
    const executionId = event.instanceId;

    // Helper for tracing back to TNF API
    const trace = async (nodeId: string, status: string, data?: any) => {
      try {
        await fetch(env.TNF_API_URL + '/api/workflows/trace', {
          method: 'POST',
          headers: { 
            'Content-Type': 'application/json',
            'Authorization': \`Bearer \${env.TNF_API_KEY || ''}\`
          },
          body: JSON.stringify({
            executionId,
            workflowId: "${workflow.id}",
            nodeId,
            status,
            data,
            timestamp: new Date().toISOString()
          })
        });
      } catch (e) {
        console.error("Failed to send trace:", e);
      }
    };

    await trace("start", "workflow_started", { input: event.payload });

${runBody}
    
    await trace("end", "workflow_completed", { finalContext: context });
    return { status: "completed", finalContext: context };
  }
}
`.trim();
  }

  /**
   * Recursively generate code for a chain of nodes.
   */
  private generateNodeChain(
    currentNode: WorkflowNode,
    workflow: UnifiedWorkflow,
    visited: Set<string>
  ): string {
    if (visited.has(currentNode.id)) return '    // Circular reference detected or path merged\n';
    visited.add(currentNode.id);

    let code = '';

    // 1. Generate code for current node
    if (
      currentNode.type !== WorkflowNodeType.START &&
      currentNode.type !== WorkflowNodeType.INPUT &&
      currentNode.type !== WorkflowNodeType.END &&
      currentNode.type !== WorkflowNodeType.OUTPUT
    ) {
      code += this.transpileNode(currentNode);
    }

    // 2. Determine next steps
    const outgoingConnections = workflow.definition.connections.filter(
      (c) => c.sourceNodeId === currentNode.id
    );

    if (currentNode.type === WorkflowNodeType.CONDITION) {
      const trueEdge = outgoingConnections.find(
        (c) => c.sourceHandle === 'true' || c.sourceHandle === 'output'
      );
      const falseEdge = outgoingConnections.find((c) => c.sourceHandle === 'false');

      const config = (currentNode.config as any) || {};
      const expression = config.expression || 'true';

      code += `
    // Condition: ${currentNode.name}
    if (${expression}) {
      await trace("${currentNode.id}", "condition_true");
${trueEdge ? this.generateNodeChain(this.findNode(trueEdge.targetNodeId, workflow), workflow, new Set(visited)) : '      // No true path'}
    } else {
      await trace("${currentNode.id}", "condition_false");
${falseEdge ? this.generateNodeChain(this.findNode(falseEdge.targetNodeId, workflow), workflow, new Set(visited)) : '      // No false path'}
    }
`;
      return code;
    }

    if (currentNode.type === WorkflowNodeType.LOOP) {
      const loopEdge = outgoingConnections.find(
        (c) => c.sourceHandle === 'loop' || c.sourceHandle === 'output'
      );
      const exitEdge = outgoingConnections.find((c) => c.sourceHandle === 'exit');

      const config = (currentNode.config as any) || {};
      const iterable = config.iterableVariable || 'context.items';
      const itemVar = config.itemVariable || 'item';

      code += `
    // Loop: ${currentNode.name}
    await trace("${currentNode.id}", "loop_started");
    if (Array.isArray(${iterable})) {
      for (const ${itemVar} of ${iterable}) {
        context.${itemVar} = ${itemVar};
${loopEdge ? this.generateNodeChain(this.findNode(loopEdge.targetNodeId, workflow), workflow, new Set(visited)) : '        // No loop path'}
        
        // Check break condition if defined
        ${config.breakCondition ? `if (${config.breakCondition}) break;` : ''}
      }
    }
    await trace("${currentNode.id}", "loop_completed");
${exitEdge ? this.generateNodeChain(this.findNode(exitEdge.targetNodeId, workflow), workflow, visited) : ''}
`;
      return code;
    }

    if (currentNode.type === WorkflowNodeType.PARALLEL) {
      const parallelBranches = outgoingConnections.map((c) =>
        this.generateNodeChain(this.findNode(c.targetNodeId, workflow), workflow, new Set(visited))
      );

      code += `
    // Parallel Execution: ${currentNode.name}
    await trace("${currentNode.id}", "parallel_started");
    await Promise.all([
${parallelBranches.map((branch) => `      (async () => {\n${branch}\n      })()`).join(',\n')}
    ]);
    await trace("${currentNode.id}", "parallel_completed");
`;
      return code;
    }

    // Default linear flow
    if (outgoingConnections.length > 0) {
      const nextNode = this.findNode(outgoingConnections[0].targetNodeId, workflow);
      code += this.generateNodeChain(nextNode, workflow, visited);
    }

    return code;
  }

  private transpileNode(node: WorkflowNode): string {
    const config = (node.config as any) || {};
    const stepName = config.stepName || this.sanitizeStepName(node.name);
    const nodeId = node.id;

    switch (node.type) {
      case WorkflowNodeType.AGENT:
      case WorkflowNodeType.AGENT_TASK:
        const agentType = config.agentType || 'claude';
        return `
    await trace("${nodeId}", "node_started", { agentType: "${agentType}" });
    context.${stepName} = await step.do("${stepName}", { retries: { limit: 3, delay: "10s" } }, async () => {
      const res = await fetch(env.TNF_API_URL + '/api/agent/trigger', {
         method: 'POST',
         headers: { 
           'Content-Type': 'application/json',
           'Authorization': \`Bearer \${env.TNF_API_KEY || ''}\`
         },
         body: JSON.stringify({ 
           task: \`${config.task || config.prompt || ''}\`,
           agentType: "${agentType}",
           context: context
         })
      });
      if (!res.ok) throw new Error(\`TNF Agent trigger failed: \${res.status}\`);
      return await res.json();
    });
    await trace("${nodeId}", "node_completed", { output: context.${stepName} });
`;

      case WorkflowNodeType.MCP_TOOL:
        return `
    await trace("${nodeId}", "node_started", { mcpServer: "${config.mcpServer}", tool: "${config.tool}" });
    context.${stepName} = await step.do("${stepName}", async () => {
      const res = await fetch(env.TNF_API_URL + '/api/mcp/execute', {
         method: 'POST',
         headers: { 
           'Content-Type': 'application/json',
           'Authorization': \`Bearer \${env.TNF_API_KEY || ''}\`
         },
         body: JSON.stringify({ 
           server: "${config.mcpServer}",
           tool: "${config.tool}",
           arguments: ${typeof config.parameters === 'string' ? config.parameters : JSON.stringify(config.parameters || {})}
         })
      });
      if (!res.ok) throw new Error(\`MCP Tool execution failed: \${res.status}\`);
      return await res.json();
    });
    await trace("${nodeId}", "node_completed", { output: context.${stepName} });
`;

      case WorkflowNodeType.TRANSFORM:
        const transformType = config.transformType || 'javascript';
        return `
    await trace("${nodeId}", "node_started", { transformType: "${transformType}" });
    context.${stepName} = await step.do("${stepName}", async () => {
      const input = context;
      ${
        transformType === 'javascript'
          ? `
      // Inline JS Transform
      const transform = (data) => {
        ${config.code || 'return data;'}
      };
      return transform(input);
      `
          : `
      // Template Transform
      return \`${config.template || ''}\`.replace(/{{(.+?)}}/g, (_, g) => input[g.trim()] || '');
      `
      }
    });
    await trace("${nodeId}", "node_completed", { output: context.${stepName} });
`;

      case WorkflowNodeType.NOTIFICATION:
        return `
    await trace("${nodeId}", "node_started", { channel: "${config.channel}" });
    await step.do("${stepName}", async () => {
      await fetch(env.TNF_API_URL + '/api/notifications/send', {
         method: 'POST',
         headers: { 
           'Content-Type': 'application/json',
           'Authorization': \`Bearer \${env.TNF_API_KEY || ''}\`
         },
         body: JSON.stringify({ 
           channel: "${config.channel || 'ui'}",
           message: \`${config.message || ''}\`,
           recipient: "${config.recipient || ''}",
           context: context
         })
      });
    });
    await trace("${nodeId}", "node_completed");
`;

      case WorkflowNodeType.API_CALL:
        return `
    await trace("${nodeId}", "node_started", { url: "${config.url}" });
    context.${stepName} = await step.do("${stepName}", async () => {
      const res = await fetch("${config.url}", {
         method: "${config.method || 'GET'}",
         headers: ${JSON.stringify(config.headers || {})},
         ${config.body ? `body: JSON.stringify(${JSON.stringify(config.body)})` : ''}
      });
      return await res.json();
    });
    await trace("${nodeId}", "node_completed");
`;

      default:
        return `    // Node: ${node.name} (${node.type}) - No implementation yet\n`;
    }
  }

  private findNode(id: string, workflow: UnifiedWorkflow): WorkflowNode {
    const node = workflow.definition.nodes.find((n) => n.id === id);
    if (!node) throw new Error(`Node not found: ${id}`);
    return node;
  }

  private sanitizeClassName(name: string): string {
    return name.replace(/[^a-zA-Z0-9]/g, '') || 'TnfWorkflow';
  }

  private sanitizeStepName(name: string): string {
    return name.replace(/[^a-zA-Z0-9_]/g, '_').toLowerCase() || 'step';
  }
}
