apiVersion: v1
kind: ServiceAccount
metadata:
  name: sync-core
  namespace: the-new-fuse
  labels:
    app: sync-core

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sync-core-role
  namespace: the-new-fuse
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sync-core-rolebinding
  namespace: the-new-fuse
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sync-core-role
subjects:
  - kind: ServiceAccount
    name: sync-core
    namespace: the-new-fuse
