import { timedelta } from './timedelta.js';
declare class Config {
    SECRET_KEY: string;
    SQLALCHEMY_DATABASE_URI: string;
    SQLALCHEMY_TRACK_MODIFICATIONS: boolean;
    REDIS_HOST: string;
    REDIS_PORT: number;
    REDIS_DB: number;
    REDIS_PASSWORD: string | undefined;
    REDIS_SSL: boolean;
    REDIS_TIMEOUT: number;
    SESSION_TYPE: string;
    PERMANENT_SESSION_LIFETIME: timedelta;
    SESSION_REDIS_HOST: string;
    SESSION_REDIS_PORT: number;
    SESSION_REDIS_DB: number;
    SESSION_REDIS_PASSWORD: string | undefined;
    SESSION_REDIS_SSL: boolean;
    RATELIMIT_STORAGE_URL: string;
    RATELIMIT_STRATEGY: string;
    RATELIMIT_DEFAULT: string;
    ENCRYPTION_KEY: string | Buffer;
    ACCESS_TOKEN_EXPIRE_MINUTES: number;
    REFRESH_TOKEN_EXPIRE_DAYS: number;
    JWT_ALGORITHM: string;
    SMTP_SERVER: string;
    SMTP_PORT: number;
    SMTP_USERNAME: string | undefined;
    SMTP_PASSWORD: string | undefined;
    SMTP_FROM_EMAIL: string;
    MIN_PASSWORD_LENGTH: number;
    PASSWORD_REQUIRE_SPECIAL: boolean;
    PASSWORD_REQUIRE_NUMBERS: boolean;
    MAX_LOGIN_ATTEMPTS: number;
    LOCKOUT_DURATION_MINUTES: number;
    REQUIRE_EMAIL_VERIFICATION: boolean;
}
export declare function get_settings<T extends Config>(): T;
export {};
