import { Schedule } from '../types';
  name:Component Analysis Schedule'
  description:Runs component analysis daily to track changes in component usage'
  type: 'recurring'
    name:Daily Component Analysis'
    description:Analyzes component usage and tracks changes over time'
    priority: ''
    cron:0 0 * * *'
    owner: 'system'
    category: ''