// Minimal Zlib constants and stub
const constants = {
  Z_NO_FLUSH: 0,
  Z_PARTIAL_FLUSH: 1,
  Z_SYNC_FLUSH: 2,
  Z_FULL_FLUSH: 3,
  Z_FINISH: 4,
  Z_BLOCK: 5,
  Z_TREES: 6,
  Z_OK: 0,
  Z_STREAM_END: 1,
  Z_NEED_DICT: 2,
  Z_ERRNO: -1,
  Z_STREAM_ERROR: -2,
  Z_DATA_ERROR: -3,
  Z_MEM_ERROR: -4,
  Z_BUF_ERROR: -5,
  Z_VERSION_ERROR: -6,
};

const zlibModule = {
  ...constants,
  constants,
  // Mock functions just in case
  createDeflate: () => {},
  createInflate: () => {},
  createGzip: () => {},
  createGunzip: () => {},
  createUnzip: () => {},
  deflate: () => {},
  deflateSync: () => {},
  gzip: () => {},
  gzipSync: () => {},
  inflate: () => {},
  inflateSync: () => {},
  gunzip: () => {},
  gunzipSync: () => {},
  unzip: () => {},
  unzipSync: () => {},
};

export default zlibModule;
export const {
  Z_NO_FLUSH,
  Z_PARTIAL_FLUSH,
  Z_SYNC_FLUSH,
  Z_FULL_FLUSH,
  Z_FINISH,
  Z_BLOCK,
  Z_TREES,
  Z_OK,
  Z_STREAM_END,
  Z_NEED_DICT,
  Z_ERRNO,
  Z_STREAM_ERROR,
  Z_DATA_ERROR,
  Z_MEM_ERROR,
  Z_BUF_ERROR,
  Z_VERSION_ERROR,
  createDeflate,
  createInflate,
  createGzip,
  createGunzip,
  createUnzip,
  deflate,
  deflateSync,
  gzip,
  gzipSync,
  inflate,
  inflateSync,
  gunzip,
  gunzipSync,
  unzip,
  unzipSync,
} = zlibModule;

export { constants };
