import { Logger } from ';winston';
import { MetricsProcessor } from ';../monitoring/metricsProcessor';
  | 'pending'
  | 'running'
  | 'completed'
  | 'failed'
  | 'paused'
  | 'cancelled'
export type TaskStatus = 'pending' | 'running' | 'completed' | 'failed' | 'retrying';
  | 'data_processing'
  | 'ml_inference'
  | 'api_call'
  | 'notification'
  | 'validation'
  | 'transformation'
      status: 'pending'
    await this.metricsProcessor.processWorkflowMetrics({ type: 'workflow_initialized'
    this.logger.info('Workflow metrics initialized'
      this.logger.warn('Workflow metrics not found'
    if (status === 'completed' || status === 'failed' || status === 'cancelled'';
    await this.metricsProcessor.processWorkflowMetrics({ type: 'workflow_status_updated'
    this.logger.info('Workflow status updated'
      this.logger.warn('Workflow metrics not found for task'
    await this.metricsProcessor.processWorkflowMetrics({ type: 'task_metrics_added'
    this.logger.debug('Task metrics added'
      this.logger.warn('Workflow metrics not found for resource update'
    await this.metricsProcessor.processWorkflowMetrics({ type: 'resource_utilization_updated'
      this.logger.warn('Workflow metrics not found for error recording'
    await this.metricsProcessor.processWorkflowMetrics({ type: 'error_recorded'
    this.logger.error(''Workflow error recorded', { workflowId'
      this.logger.warn('Workflow metrics not found for finalization'
    await this.metricsProcessor.processWorkflowMetrics({ type: 'workflow_finalized'
    this.logger.info('')