
-- ============================================================
-- TNF Marketplace Seed Data - Full AI Agent Stack
-- ============================================================
-- Kinds: agent, agent_template, experience, mcp_server, model, prompt, skill, workflow
-- Mix of free (price_per_run=0) and paid (price_per_run>0) assets

INSERT INTO marketplace_catalog_items (id, slug, name, description, kind, category, tags, capabilities, rating, total_runs, success_rate, price_per_run, status, publication_status, launch_url, avatar_url, created_by, created_at, updated_at)
VALUES

-- ===== AGENTS (complete autonomous agents) =====
('agent-coding-orchestrator', 'coding-orchestrator', 'Coding Orchestrator', 'Autonomous multi-agent coding orchestrator that decomposes complex development tasks into parallel subagent workstreams. Delegates to specialist agents for code review, testing, and deployment. Supports Claude Code, Codex, and OpenCode backends.', 'agent', 'development', '["agent", "coding", "orchestration", "multi-agent", "autonomous"]', '["code_generation", "task_decomposition", "parallel_delegation", "pr_review", "test_execution"]', 4.8, 45230, 97.2, 0.02, 'online', 'published', 'https://github.com/anthropics/claude-code', NULL, 'tnf-curator', NOW(), NOW()),

('agent-research-scout', 'research-scout', 'Research Scout', 'Autonomous web research agent that discovers, crawls, and synthesizes information from academic papers, documentation, and code repositories. Returns structured intelligence artifacts with provenance tracking.', 'agent', 'research', '["agent", "research", "crawling", "synthesis", "academic"]', '["web_crawling", "paper_search", "data_synthesis", "provenance_tracking", "structured_output"]', 4.7, 31200, 96.8, 0, 'online', 'published', NULL, NULL, 'tnf-curator', NOW(), NOW()),

('agent-infrastructure-monitor', 'infrastructure-monitor', 'Infrastructure Monitor', 'Continuously monitors cloud infrastructure health, detects anomalies, and autonomously remediates common failure patterns. Supports AWS, GCP, CloudRuntime, and Cloudflare with zero-config onboarding.', 'agent', 'devops', '["agent", "infrastructure", "monitoring", "cloud", "remediation"]', '["health_monitoring", "anomaly_detection", "auto_remediation", "multi_cloud", "alerting"]', 4.6, 28450, 95.1, 0.015, 'online', 'published', NULL, NULL, 'tnf-curator', NOW(), NOW()),

('agent-data-pipeline', 'data-pipeline-agent', 'Data Pipeline Agent', 'ETL orchestrator that builds, monitors, and repairs data pipelines. Auto-schemas new sources, handles schema drift, and maintains lineage tracking across transformations.', 'agent', 'data', '["agent", "etl", "pipeline", "data", "orchestration"]', '["etl_orchestration", "schema_detection", "drift_handling", "lineage_tracking", "error_recovery"]', 4.5, 19870, 94.3, 0.01, 'online', 'published', NULL, NULL, 'tnf-curator', NOW(), NOW()),

('agent-customer-support', 'customer-support-agent', 'Customer Support Agent', 'AI customer support agent with RAG-powered knowledge base, ticket classification, and escalation logic. Handles multi-turn conversations with context persistence and sentiment analysis.', 'agent', 'support', '["agent", "support", "rag", "classification", "escalation"]', '["rag_retrieval", "ticket_classification", "sentiment_analysis", "multi_turn_conversation", "escalation_logic"]', 4.4, 62100, 93.7, 0.005, 'online', 'published', NULL, NULL, 'tnf-curator', NOW(), NOW()),

('agent-security-scanner', 'security-scanner-agent', 'Security Scanner Agent', 'Autonomous security audit agent that scans codebases, APIs, and infrastructure for vulnerabilities. Generates CWE-classified reports with remediation steps and severity scoring.', 'agent', 'security', '["agent", "security", "scanning", "audit", "vulnerability"]', '["vulnerability_scanning", "cwe_classification", "remediation_advice", "severity_scoring", "compliance_check"]', 4.6, 15340, 96.2, 0.025, 'online', 'published', NULL, NULL, 'tnf-curator', NOW(), NOW()),

('agent-content-writer', 'content-writer-agent', 'Content Writer Agent', 'SEO-optimized content generation agent with brand voice calibration, fact-checking pipeline, and multi-format output (blog, social, email). Includes plagiarism detection and readability scoring.', 'agent', 'content', '["agent", "writing", "seo", "content", "generation"]', '["content_generation", "brand_voice_calibration", "fact_checking", "plagiarism_detection", "readability_scoring"]', 4.3, 41200, 92.8, 0.008, 'online', 'published', NULL, NULL, 'tnf-curator', NOW(), NOW()),

-- ===== AGENT TEMPLATES (operative blueprints) =====
('template-reasoning-chain', 'reasoning-chain-template', 'Reasoning Chain Template', 'Configurable chain-of-thought agent template with step-by-step reasoning, self-verification, and confidence scoring. Customize for any analytical or decision-making domain.', 'agent_template', 'reasoning', '["template", "reasoning", "chain-of-thought", "verification", "configurable"]', '["chain_of_thought", "self_verification", "confidence_scoring", "customizable_pipeline"]', 4.7, 54300, 97.5, 0, 'online', 'published', NULL, NULL, 'tnf-curator', NOW(), NOW()),

('template-rag-pipeline', 'rag-pipeline-template', 'RAG Pipeline Template', 'Production-ready Retrieval-Augmented Generation template with vector search, re-ranking, and citation tracking. Drop in your documents and get accurate, sourced answers.', 'agent_template', 'knowledge', '["template", "rag", "retrieval", "vector-search", "citations"]', '["document_ingestion", "vector_search", "re_ranking", "citation_tracking", "chunk_optimization"]', 4.8, 71200, 98.1, 0, 'online', 'published', NULL, NULL, 'tnf-curator', NOW(), NOW()),

('template-tool-caller', 'tool-caller-template', 'Tool Caller Template', 'Agent template with structured tool-use patterns including retry logic, schema validation, and parallel execution. Pre-wired for MCP, REST, and CLI tool integrations.', 'agent_template', 'tools', '["template", "tools", "mcp", "api", "integration"]', '["tool_calling", "retry_logic", "schema_validation", "parallel_execution", "mcp_integration"]', 4.6, 38900, 96.4, 0, 'online', 'published', NULL, NULL, 'tnf-curator', NOW(), NOW()),

('template-multi-agent-swarm', 'multi-agent-swarm-template', 'Multi-Agent Swarm Template', 'Template for deploying parallel specialist agents with different LLM providers for resilience and perspective diversity. Built-in result aggregation, conflict resolution, and consensus scoring.', 'agent_template', 'orchestration', '["template", "swarm", "multi-agent", "parallel", "consensus"]', '["parallel_deployment", "result_aggregation", "conflict_resolution", "consensus_scoring", "provider_diversity"]', 4.5, 22100, 95.0, 0, 'online', 'published', NULL, NULL, 'tnf-curator', NOW(), NOW()),

('template-rl-fine-tuner', 'rl-fine-tuner-template', 'RL Fine-Tuner Template', 'Reinforcement learning fine-tuning template with GRPO/DPO training loops, evaluation harness, and model registry integration. Supports TRL, Axolotl, and Unsloth backends.', 'agent_template', 'ml-ops', '["template", "fine-tuning", "rl", "grpo", "dpo"]', '["rl_training", "evaluation_harness", "model_registry", "distributed_training", "hyperparameter_search"]', 4.4, 12400, 94.2, 0.02, 'online', 'published', NULL, NULL, 'tnf-curator', NOW(), NOW()),

-- ===== MCP SERVERS (hardware hubs) =====
('mcp-github-official', 'github-mcp-server-official', 'GitHub MCP Server (Official)', 'Official GitHub MCP server providing full API access: issues, PRs, code search, actions, and repository management. Maintained by GitHub with real-time webhook support.', 'mcp_server', 'developer-tools', '["mcp", "github", "api", "issues", "prs"]', '["issue_management", "pr_workflow", "code_search", "actions_ci", "webhook_handling"]', 4.9, 112000, 99.1, 0, 'online', 'published', 'https://github.com/github/github-mcp-server', NULL, 'tnf-curator', NOW(), NOW()),

('mcp-postgres', 'postgres-mcp-server', 'PostgreSQL MCP Server', 'Full PostgreSQL database access through MCP. Schema introspection, query execution, migration management, and real-time change notifications via logical replication.', 'mcp_server', 'databases', '["mcp", "postgresql", "database", "sql", "query"]', '["schema_introspection", "query_execution", "migration_management", "change_notifications", "connection_pooling"]', 4.7, 67300, 98.3, 0, 'online', 'published', 'https://github.com/modelcontextprotocol/servers/tree/main/src/postgres', NULL, 'tnf-curator', NOW(), NOW()),

('mcp-brave-search', 'brave-search-mcp-server', 'Brave Search MCP Server', 'Web search through Brave Search API with result summarization, local business search, and scholarly article discovery. Rate-limited with automatic pagination.', 'mcp_server', 'search', '["mcp", "search", "web", "brave", "api"]', '["web_search", "result_summarization", "local_search", "scholarly_search", "pagination"]', 4.6, 54200, 97.8, 0, 'online', 'published', 'https://github.com/modelcontextprotocol/servers/tree/main/src/brave_search', NULL, 'tnf-curator', NOW(), NOW()),

('mcp-puppeteer', 'puppeteer-mcp-server', 'Puppeteer MCP Server', 'Browser automation via MCP using Puppeteer. Navigate, screenshot, click, fill forms, and extract content from any web page. Supports stealth mode and proxy rotation.', 'mcp_server', 'browser', '["mcp", "puppeteer", "browser", "automation", "scraping"]', '["browser_navigation", "screenshot_capture", "form_interaction", "content_extraction", "stealth_mode"]', 4.5, 43100, 96.5, 0, 'online', 'published', 'https://github.com/modelcontextprotocol/servers/tree/main/src/puppeteer', NULL, 'tnf-curator', NOW(), NOW()),

('mcp-memory', 'memory-mcp-server', 'Knowledge Graph Memory MCP Server', 'Persistent knowledge graph for AI agents via MCP. Store entities, relations, and observations with semantic search. Enables long-term memory across conversations.', 'mcp_server', 'memory', '["mcp", "memory", "knowledge-graph", "entities", "relations"]', '["entity_storage", "relation_mapping", "semantic_search", "observation_logging", "cross_session_persistence"]', 4.8, 78900, 99.0, 0, 'online', 'published', 'https://github.com/modelcontextprotocol/servers/tree/main/src/memory', NULL, 'tnf-curator', NOW(), NOW()),

('mcp-slack', 'slack-mcp-server', 'Slack MCP Server', 'Slack workspace integration through MCP. Send messages, read channels, manage threads, and search messages. Supports both bot and user tokens with workspace administration.', 'mcp_server', 'communication', '["mcp", "slack", "messaging", "channels", "workspace"]', '["message_sending", "channel_reading", "thread_management", "message_search", "workspace_admin"]', 4.4, 31200, 95.7, 0.005, 'online', 'published', 'https://github.com/modelcontextprotocol/servers/tree/main/src/slack', NULL, 'tnf-curator', NOW(), NOW()),

('mcp-sentry', 'sentry-mcp-server', 'Sentry MCP Server', 'Error tracking and performance monitoring through MCP. Query issues, trace transactions, analyze crash reports, and manage release health from any AI agent.', 'mcp_server', 'observability', '["mcp", "sentry", "errors", "monitoring", "tracing"]', '["issue_querying", "transaction_tracing", "crash_analysis", "release_health", "performance_monitoring"]', 4.3, 18700, 94.8, 0, 'online', 'published', NULL, NULL, 'tnf-curator', NOW(), NOW()),

('mcp-sequential-thinking', 'sequential-thinking-mcp-server', 'Sequential Thinking MCP Server', 'Structured reasoning engine via MCP. Break complex problems into sequential thinking steps with revision support, branching, and thought summarization.', 'mcp_server', 'reasoning', '["mcp", "thinking", "reasoning", "structured", "sequential"]', '["sequential_reasoning", "thought_branching", "revision_support", "thought_summarization", "problem_decomposition"]', 4.7, 45600, 98.5, 0, 'online', 'published', NULL, NULL, 'tnf-curator', NOW(), NOW()),

('mcp-everything', 'everything-mcp-server', 'Everything MCP Server', 'Reference MCP server implementing all protocol features. Use for testing, learning MCP, and as a template for building custom servers. Includes prompts, resources, tools, and sampling.', 'mcp_server', 'reference', '["mcp", "reference", "testing", "template", "protocol"]', '["all_protocol_features", "testing_support", "prompt_templates", "resource_serving", "sampling"]', 4.5, 29800, 97.2, 0, 'online', 'published', NULL, NULL, 'tnf-curator', NOW(), NOW()),

('mcp-cloudflare-workers', 'cloudflare-workers-mcp-server', 'Cloudflare Workers MCP Server', 'Deploy and manage Cloudflare Workers, KV stores, D1 databases, and R2 storage through MCP. Full Wrangler CLI integration from any AI agent.', 'mcp_server', 'cloud-infrastructure', '["mcp", "cloudflare", "workers", "kv", "d1"]', '["worker_deployment", "kv_management", "d1_database", "r2_storage", "wrangler_integration"]', 4.4, 22100, 95.3, 0, 'online', 'published', NULL, NULL, 'tnf-curator', NOW(), NOW()),

-- ===== MODELS (neural backbones) =====
('model-claude-sonnet-4', 'claude-sonnet-4', 'Claude Sonnet 4', 'Anthropic flagship reasoning model with 200K context, tool use, and vision. Top-tier code generation, analysis, and complex reasoning with constitutional AI safety.', 'model', 'reasoning', '["model", "anthropic", "reasoning", "code", "vision"]', '["200k_context", "tool_use", "vision", "constitutional_ai", "structured_output"]', 4.9, 892000, 99.3, 0.003, 'online', 'published', 'https://docs.anthropic.com', NULL, 'tnf-curator', NOW(), NOW()),

('model-gemini-25-pro', 'gemini-25-pro', 'Gemini 2.5 Pro', 'Google DeepMind reasoning model with 1M token context, native multimodal understanding, and built-in code execution. Best-in-class long-context performance.', 'model', 'reasoning', '["model", "google", "multimodal", "long-context", "code-execution"]', '["1m_context", "native_multimodal", "code_execution", "grounded_search", "structured_output"]', 4.8, 756000, 98.9, 0.0025, 'online', 'published', 'https://ai.google.dev', NULL, 'tnf-curator', NOW(), NOW()),

('model-gpt-4-1', 'gpt-4-1', 'GPT-4.1', 'OpenAI GPT-4.1 with improved instruction following, 1M context, and agentic capabilities. Excels at complex multi-step tasks with native function calling.', 'model', 'reasoning', '["model", "openai", "instruction-following", "agentic", "function-calling"]', '["1m_context", "function_calling", "agentic_reasoning", "structured_output", "json_mode"]', 4.8, 923000, 99.0, 0.002, 'online', 'published', 'https://platform.openai.com', NULL, 'tnf-curator', NOW(), NOW()),

('model-llama-33-70b', 'llama-33-70b-instruct', 'Llama 3.3 70B Instruct', 'Meta open-weight 70B instruction model. Strong reasoning and code generation at a fraction of proprietary model cost. Self-hostable with vLLM or llama.cpp.', 'model', 'open-source', '["model", "meta", "llama", "open-source", "self-hostable"]', '["self_hostable", "vllm_compatible", "llama_cpp", "70b_parameters", "instruction_tuned"]', 4.5, 534000, 96.8, 0, 'online', 'published', 'https://huggingface.co/meta-llama/Llama-3.3-70B-Instruct', NULL, 'tnf-curator', NOW(), NOW()),

('model-deepseek-v4', 'deepseek-v4-pro', 'DeepSeek V4 Pro', 'DeepSeek V4 with Mixture-of-Experts architecture. Excellent at math, code, and multilingual tasks with aggressive pricing. Top open-weight competitor to GPT-4 class models.', 'model', 'open-source', '["model", "deepseek", "moe", "code", "math"]', '["moe_architecture", "math_reasoning", "code_generation", "multilingual", "cost_effective"]', 4.6, 412000, 97.1, 0, 'online', 'published', 'https://huggingface.co/deepseek-ai', NULL, 'tnf-curator', NOW(), NOW()),

('model-glm-5-1', 'glm-5-1', 'GLM-5.1', 'Zhipu AI GLM-5.1 with strong bilingual (Chinese/English) capabilities. Competitive performance on reasoning benchmarks with free tier availability via NVIDIA API.', 'model', 'open-source', '["model", "zhipu", "chinese", "bilingual", "nvidia"]', '["bilingual_support", "reasoning", "free_tier", "nvidia_api", "structured_output"]', 4.3, 287000, 95.4, 0, 'online', 'published', NULL, NULL, 'tnf-curator', NOW(), NOW()),

('model-e5-large-instruct', 'e5-large-instruct', 'E5 Large Instruct', 'Microsoft E5-large-instruct embedding model. 1024 dimensions, free, and production-proven for RAG similarity search. Outperforms paid alternatives in retrieval benchmarks.', 'model', 'embeddings', '["model", "embedding", "e5", "microsoft", "rag"]', '["1024_dimensions", "similarity_search", "rag_optimized", "free_tier", "production_proven"]', 4.7, 234000, 99.5, 0, 'online', 'published', 'https://huggingface.co/intfloat/e5-large-instruct', NULL, 'tnf-curator', NOW(), NOW()),

-- ===== SKILLS (sensory & skills) =====
('skill-webpilot', 'webpilot-browser-automation', 'WebPilot Browser Automation', 'CDP-free browser automation via Chrome extension + WebSocket relay. Navigate, scrape, fill forms, and interact with web pages without automation fingerprints. Built-in honeypot detection.', 'skill', 'browser', '["skill", "browser", "automation", "scraping", "stealth"]', '["browser_automation", "web_scraping", "form_filling", "honeypot_detection", "bezier_mouse"]', 4.8, 56200, 98.7, 0, 'online', 'published', NULL, NULL, 'tnf-curator', NOW(), NOW()),

('skill-concordance-search', 'concordance-search', 'Concordance Search', 'Codebase concordance with 149K identifiers across 8,904 source files. Query identifier frequencies, power phrases, and communication patterns via MCP server or REST API.', 'skill', 'codebase', '["skill", "concordance", "search", "identifiers", "codebase"]', '["identifier_search", "power_phrases", "frequency_analysis", "file_density", "category_browsing"]', 4.5, 23400, 97.2, 0, 'online', 'published', NULL, NULL, 'tnf-curator', NOW(), NOW()),

('skill-sspdf-gen', 'sspdf-generation', 'SSPDF Document Generation', 'Declarative PDF generation engine. JSON source + theme = pixel-perfect PDF. Supports invoices, reports, articles with custom themes and automatic pagination.', 'skill', 'documents', '["skill", "pdf", "generation", "documents", "templates"]', '["pdf_generation", "json_to_pdf", "theme_engine", "automatic_pagination", "custom_fonts"]', 4.6, 31200, 98.1, 0, 'online', 'published', NULL, NULL, 'tnf-curator', NOW(), NOW()),

('skill-model-watchdog', 'model-health-watchdog', 'Model Health Watchdog', 'Autonomous 3-minute auto-failover monitoring for LLM API providers. Active probing, latency tracking, and automatic fallback routing across NVIDIA, OpenRouter, and local inference.', 'skill', 'monitoring', '["skill", "monitoring", "llm", "failover", "health"]', '["active_probing", "latency_tracking", "auto_failover", "provider_characterization", "fallback_routing"]', 4.7, 42100, 99.1, 0, 'online', 'published', NULL, NULL, 'tnf-curator', NOW(), NOW()),

('skill-continuous-correction', 'continuous-correction-flywheel', 'Continuous Correction Flywheel', 'Self-healing QA/fix flywheel that deploys parallel specialist agents using different LLM providers. Visual QA, codebase audit, and infrastructure audit with detailed logging.', 'skill', 'quality', '["skill", "qa", "correction", "flywheel", "self-healing"]', '["parallel_agents", "visual_qa", "codebase_audit", "infrastructure_audit", "automated_fixing"]', 4.6, 28700, 97.8, 0, 'online', 'published', NULL, NULL, 'tnf-curator', NOW(), NOW()),

('skill-kanban-orchestrator', 'kanban-orchestrator', 'Kanban Orchestrator', 'Task decomposition playbook with anti-temptation rules for orchestrating multi-step agent work. Breaks complex goals into atomic work items with dependency tracking and progress reporting.', 'skill', 'planning', '["skill", "kanban", "planning", "decomposition", "orchestration"]', '["task_decomposition", "dependency_tracking", "progress_reporting", "anti_temptation", "work_item_management"]', 4.4, 19800, 96.5, 0, 'online', 'published', NULL, NULL, 'tnf-curator', NOW(), NOW()),

('skill-mcp-bridge', 'mcp-bridge', 'MCP Bridge', 'Bridge skill for connecting external tools and MCP servers to internal TNF endpoints. Configures server discovery, tool registration, and bidirectional communication.', 'skill', 'integration', '["skill", "mcp", "bridge", "tools", "integration"]', '["mcp_server_connection", "tool_registration", "server_discovery", "bidirectional_comm", "protocol_bridging"]', 4.5, 25400, 97.3, 0, 'online', 'published', NULL, NULL, 'tnf-curator', NOW(), NOW()),

('skill-voice-bridge', 'voice-bridge', 'Bidirectional Voice Bridge', 'End-to-end bidirectional native voice bridge connecting Whisper STT to TTS engines. Supports Edge TTS, OpenAI TTS, and custom voice providers with circuit-breaker resilience.', 'skill', 'audio', '["skill", "voice", "stt", "tts", "bridge"]', '["speech_to_text", "text_to_speech", "voice_selection", "circuit_breaker", "realtime_streaming"]', 4.3, 14200, 95.6, 0, 'online', 'published', NULL, NULL, 'tnf-curator', NOW(), NOW()),

-- ===== PROMPTS (prompt packs) =====
('prompt-system-architect', 'system-architect-prompts', 'System Architect Prompt Pack', 'Curated collection of 25 system architecture prompts covering microservices, event-driven design, CQRS, and distributed systems patterns. Each prompt includes context scaffolding and output format constraints.', 'prompt', 'architecture', '["prompt", "architecture", "system-design", "microservices", "distributed"]', '["architecture_design", "pattern_selection", "tradeoff_analysis", "scalability_planning", "diagram_generation"]', 4.7, 34500, 97.9, 0, 'online', 'published', NULL, NULL, 'tnf-curator', NOW(), NOW()),

('prompt-code-review-suite', 'code-review-prompt-suite', 'Code Review Prompt Suite', '18 battle-tested code review prompts covering security, performance, readability, and API design. Includes language-specific variants for TypeScript, Python, Rust, and Go.', 'prompt', 'development', '["prompt", "code-review", "security", "performance", "multi-language"]', '["security_audit", "performance_review", "readability_check", "api_design_review", "language_specific"]', 4.6, 42100, 97.2, 0, 'online', 'published', NULL, NULL, 'tnf-curator', NOW(), NOW()),

('prompt-research-synthesizer', 'research-synthesizer-prompts', 'Research Synthesizer Prompts', '12 research-oriented prompts for literature review, paper summarization, hypothesis generation, and methodology comparison. Optimized for academic and market research contexts.', 'prompt', 'research', '["prompt", "research", "synthesis", "academic", "literature-review"]', '["literature_review", "paper_summarization", "hypothesis_generation", "methodology_comparison", "citation_extraction"]', 4.5, 21300, 96.8, 0, 'online', 'published', NULL, NULL, 'tnf-curator', NOW(), NOW()),

('prompt-product-spec-writer', 'product-spec-writer-prompts', 'Product Spec Writer Prompts', '15 product management prompts for PRDs, user stories, acceptance criteria, and competitive analysis. Includes stakeholder communication templates and roadmap frameworks.', 'prompt', 'product', '["prompt", "product", "spec", "prd", "management"]', '["prd_writing", "user_stories", "acceptance_criteria", "competitive_analysis", "roadmap_planning"]', 4.4, 28900, 96.1, 0.005, 'online', 'published', NULL, NULL, 'tnf-curator', NOW(), NOW()),

('prompt-debugging-detective', 'debugging-detective-prompts', 'Debugging Detective Prompts', '20 debugging prompts with 4-phase root cause analysis: symptom capture, hypothesis formation, systematic isolation, and verification. Covers memory leaks, race conditions, and distributed failures.', 'prompt', 'debugging', '["prompt", "debugging", "root-cause", "systematic", "troubleshooting"]', '["root_cause_analysis", "hypothesis_testing", "systematic_isolation", "verification_steps", "distributed_debugging"]', 4.8, 51300, 98.4, 0, 'online', 'published', NULL, NULL, 'tnf-curator', NOW(), NOW()),

('prompt-fine-tuning-recipe', 'fine-tuning-recipe-prompts', 'Fine-Tuning Recipe Prompts', '10 prompts for generating optimal training recipes: dataset curation, hyperparameter selection, evaluation design, and deployment strategies. Covers SFT, DPO, GRPO, and RLHF.', 'prompt', 'ml-ops', '["prompt", "fine-tuning", "training", "ml-ops", "recipes"]', '["dataset_curation", "hyperparameter_tuning", "evaluation_design", "deployment_strategy", "training_recipe"]', 4.3, 15600, 95.4, 0.01, 'online', 'published', NULL, NULL, 'tnf-curator', NOW(), NOW()),

-- ===== WORKFLOWS (synapses) =====
('wf-ci-cd-pipeline', 'ci-cd-pipeline-workflow', 'CI/CD Pipeline Workflow', 'End-to-end continuous integration and deployment workflow: lint, test, build, deploy with automatic rollback on failure. Supports GitHub Actions, Cloud Build, and CloudRuntime.', 'workflow', 'devops', '["workflow", "ci-cd", "deployment", "testing", "automation"]', '["linting", "testing", "building", "deploying", "auto_rollback"]', 4.7, 67800, 98.2, 0, 'online', 'published', NULL, NULL, 'tnf-curator', NOW(), NOW()),

('wf-data-enrichment', 'data-enrichment-workflow', 'Data Enrichment Workflow', 'Multi-stage data enrichment pipeline: fetch, clean, classify, embed, and store. Handles schema drift, deduplication, and incremental updates with quality gates at each stage.', 'workflow', 'data', '["workflow", "data", "enrichment", "pipeline", "quality"]', '["data_fetching", "cleaning", "classification", "embedding", "quality_gates"]', 4.5, 31200, 96.7, 0, 'online', 'published', NULL, NULL, 'tnf-curator', NOW(), NOW()),

('wf-security-audit-cycle', 'security-audit-cycle-workflow', 'Security Audit Cycle', 'Recurring security audit workflow: dependency scanning, SAST, DAST, secret detection, and compliance reporting. Integrates with GitHub, Sentry, and OWASP tooling.', 'workflow', 'security', '["workflow", "security", "audit", "compliance", "scanning"]', '["dependency_scanning", "sast", "dast", "secret_detection", "compliance_reporting"]', 4.6, 42100, 97.5, 0.015, 'online', 'published', NULL, NULL, 'tnf-curator', NOW(), NOW()),

('wf-content-publication', 'content-publication-workflow', 'Content Publication Workflow', 'Content lifecycle workflow: draft, review, SEO-optimize, fact-check, schedule, and publish across channels. Includes A/B testing headlines and performance tracking.', 'workflow', 'content', '["workflow", "content", "publication", "seo", "scheduling"]', '["drafting", "review", "seo_optimization", "fact_checking", "cross_channel_publishing"]', 4.3, 23400, 95.2, 0.005, 'online', 'published', NULL, NULL, 'tnf-curator', NOW(), NOW()),

('wf-agent-lifecycle', 'agent-lifecycle-workflow', 'Agent Lifecycle Management', 'Full agent lifecycle workflow: provision, configure, deploy, monitor, scale, and decommission. Handles health checks, auto-restart, and resource cleanup with audit trails.', 'workflow', 'agent-ops', '["workflow", "agent", "lifecycle", "provisioning", "monitoring"]', '["agent_provisioning", "configuration", "health_monitoring", "auto_scaling", "decommission"]', 4.5, 27800, 96.9, 0, 'online', 'published', NULL, NULL, 'tnf-curator', NOW(), NOW()),

('wf-incident-response', 'incident-response-workflow', 'Incident Response Workflow', 'Automated incident response: detect, triage, communicate, remediate, and post-mortem. PagerDuty/Slack integration with runbook execution and stakeholder notification.', 'workflow', 'operations', '["workflow", "incident", "response", "remediation", "post-mortem"]', '["incident_detection", "triage", "communication", "runbook_execution", "post_mortem"]', 4.7, 38900, 98.0, 0.02, 'online', 'published', NULL, NULL, 'tnf-curator', NOW(), NOW()),

-- ===== EXPERIENCES (curated interactive apps) =====
('exp-neon-kart-racing', 'neon-kart-racing', 'Neon Kart Racing', 'AI-powered racing game with procedurally generated tracks, adaptive difficulty, and real-time agent opponents. WebGL-rendered neon aesthetic with multiplayer lobby.', 'experience', 'gaming', '["experience", "gaming", "racing", "procedural", "webgl"]', '["procedural_generation", "adaptive_difficulty", "multiplayer", "webgl_rendering", "agent_opponents"]', 4.6, 89200, 97.1, 0, 'online', 'published', NULL, NULL, 'tnf-curator', NOW(), NOW()),

('exp-data-visualizer', 'ai-data-visualizer', 'AI Data Visualizer', 'Conversational data visualization experience. Describe what you want to see in natural language, and the AI generates interactive charts, maps, and dashboards from your data.', 'experience', 'analytics', '["experience", "visualization", "data", "charts", "conversational"]', '["natural_language_queries", "interactive_charts", "dashboard_generation", "data_import", "export_options"]', 4.5, 45600, 96.4, 0, 'online', 'published', NULL, NULL, 'tnf-curator', NOW(), NOW()),

('exp-code-arena', 'code-arena', 'Code Arena', 'Live competitive coding experience where AI agents battle to solve algorithmic challenges. Watch real-time solutions with step-by-step reasoning visualization.', 'experience', 'coding', '["experience", "coding", "competition", "algorithms", "live"]', '["competitive_coding", "agent_battles", "reasoning_visualization", "leaderboard", "challenge_library"]', 4.7, 67800, 98.3, 0.01, 'online', 'published', NULL, NULL, 'tnf-curator', NOW(), NOW()),

('exp-music-lab', 'ai-music-lab', 'AI Music Lab', 'Interactive music composition experience with AI-assisted melody generation, harmony suggestions, and real-time arrangement. Supports MIDI export and collaborative editing.', 'experience', 'music', '["experience", "music", "composition", "midi", "collaborative"]', '["melody_generation", "harmony_suggestions", "real_time_arrangement", "midi_export", "collaborative_editing"]', 4.4, 31200, 95.8, 0, 'online', 'published', NULL, NULL, 'tnf-curator', NOW(), NOW()),

('exp-prompt-playground', 'prompt-playground', 'Prompt Playground', 'Interactive prompt engineering playground with A/B testing, token counting, and model comparison. Live preview of prompt outputs across multiple LLM providers.', 'experience', 'tools', '["experience", "prompts", "testing", "comparison", "engineering"]', '["prompt_engineering", "ab_testing", "token_counting", "model_comparison", "live_preview"]', 4.8, 54300, 98.9, 0, 'online', 'published', NULL, NULL, 'tnf-curator', NOW(), NOW()),

-- ===== COLLECTIBLE / SPECIAL =====
('collective-agent-badge-genesis', 'agent-badge-genesis', 'Agent Badge Genesis', 'Limited-edition genesis collectible badge for early TNF agent adopters. Confers marketplace listing priority and exclusive access to beta agent templates.', 'experience', 'collectibles', '["collectible", "badge", "genesis", "limited-edition", "nft"]', '["badge_display", "priority_access", "beta_features", "community_status"]', 5.0, 1000, 100, 0.05, 'online', 'published', NULL, NULL, 'tnf-curator', NOW(), NOW())

ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  kind = EXCLUDED.kind,
  category = EXCLUDED.category,
  tags = EXCLUDED.tags,
  capabilities = EXCLUDED.capabilities,
  rating = EXCLUDED.rating,
  total_runs = EXCLUDED.total_runs,
  success_rate = EXCLUDED.success_rate,
  price_per_run = EXCLUDED.price_per_run,
  status = EXCLUDED.status,
  publication_status = EXCLUDED.publication_status,
  launch_url = EXCLUDED.launch_url,
  updated_at = NOW();
