ALTER TABLE "agent_registrations" ADD COLUMN "tenant_id" varchar(255);
ALTER TABLE "agent_registrations" ADD COLUMN "organization_id" varchar(255);
ALTER TABLE "agent_registrations" ADD COLUMN "agency_id" uuid;
ALTER TABLE "agent_registrations" ADD COLUMN "identity_long_term_id" varchar(255);
ALTER TABLE "agent_registrations" ADD COLUMN "identity_ephemeral_id" varchar(255);
ALTER TABLE "agent_registrations" ADD COLUMN "identity_federation_id" varchar(255);
ALTER TABLE "agent_registrations" ADD COLUMN "protocol_version" varchar(50);
ALTER TABLE "agent_registrations" ADD COLUMN "trust_tier" varchar(50);
ALTER TABLE "agent_registrations" ADD COLUMN "invite_id" uuid;
CREATE INDEX "agent_registrations_tenant_idx" ON "agent_registrations" ("tenant_id");
CREATE INDEX "agent_registrations_org_idx" ON "agent_registrations" ("organization_id");
CREATE INDEX "agent_registrations_agency_idx" ON "agent_registrations" ("agency_id");
CREATE INDEX "agent_registrations_trust_idx" ON "agent_registrations" ("trust_tier");
