#!/bin/bash
# Railway Deployment Setup Commands
# Generated: 2025-11-13
# JWT_SECRET: <JWT_SECRET>

echo "===== RAILWAY DEPLOYMENT SETUP ====="
echo ""
echo "Step 1: Link to Railway project"
echo "Run this command and select 'the-new-fuse' from the list:"
echo "  railway link"
echo ""

echo "Step 2: Check current deployment status"
echo "  railway status"
echo ""

echo "Step 3: List all services"
echo "  railway service"
echo ""

echo "===== ENVIRONMENT VARIABLE SETUP ====="
echo ""
echo "For API SERVICE (run these commands):"
echo "  railway service"
echo "  # Select 'api' from the list"
echo ""
echo "  # Add DATABASE_URL (reference to Postgres)"
echo "  railway variables set DATABASE_URL='${{Postgres.DATABASE_URL}}'"
echo ""
echo "  # Add JWT_SECRET"
echo "  railway variables set JWT_SECRET='<JWT_SECRET>'"
echo ""
echo "  # Add CORS_ORIGIN (you'll get the frontend URL after deployment)"
echo "  # railway variables set CORS_ORIGIN='https://your-frontend-url.up.railway.app'"
echo ""
echo "  # Redeploy api service"
echo "  railway up --detach"
echo ""

echo "For BACKEND SERVICE (if needed):"
echo "  railway service"
echo "  # Select 'backend' from the list"
echo ""
echo "  # Add DATABASE_URL"
echo "  railway variables set DATABASE_URL='${{Postgres.DATABASE_URL}}'"
echo ""
echo "  # Add JWT_SECRET"
echo "  railway variables set JWT_SECRET='<JWT_SECRET>'"
echo ""
echo "  # Redeploy backend service"
echo "  railway up --detach"
echo ""

echo "For API-GATEWAY SERVICE (if needed):"
echo "  railway service"
echo "  # Select 'api-gateway' from the list"
echo ""
echo "  # Add JWT_SECRET"
echo "  railway variables set JWT_SECRET='<JWT_SECRET>'"
echo ""
echo "  # Redeploy api-gateway service"
echo "  railway up --detach"
echo ""

echo "For FRONTEND SERVICE:"
echo "  railway service"
echo "  # Select 'frontend' from the list"
echo ""
echo "  # Add VITE_API_URL (you'll get the API URL after deployment)"
echo "  # railway variables set VITE_API_URL='https://your-api-url.up.railway.app'"
echo ""
echo "  # Redeploy frontend service"
echo "  railway up --detach"
echo ""

echo "===== GET SERVICE URLs ====="
echo ""
echo "To get URLs for each service:"
echo "  railway service"
echo "  # Select a service"
echo "  railway domain"
echo ""
echo "Or check in Railway dashboard:"
echo "  https://railway.com/project/453fe77c-a788-412d-8507-bc3e7bc548c3"
echo ""

echo "===== CUSTOM DOMAIN SETUP ====="
echo ""
echo "1. Go to Railway dashboard → Frontend service → Settings → Domains"
echo "2. Click '+ Custom Domain'"
echo "3. Enter: www.thenewfuse.com"
echo "4. Railway will provide a CNAME record"
echo "5. Add this to your DNS:"
echo "   Type: CNAME"
echo "   Name: www"
echo "   Value: [provided by Railway]"
echo "   TTL: 300"
echo ""

echo "===== VERIFICATION ====="
echo ""
echo "After all environment variables are set:"
echo "  1. Check all services are running: railway status"
echo "  2. Check logs: railway logs"
echo "  3. Visit your frontend URL"
echo "  4. Test sign up / login functionality"
echo ""
