import { WorkflowTemplate, WorkflowStepType, WorkflowStep } from '@the-new-fuse/types';
  id: 'agentic-communication-flow'
  name: 'Agentic Communication Flow'
  description: 'Template for agentic communication flows based on AI Diplomacy schema'
  version: ''
    startStep: 'initialize'
      id: 'initialize'
      status: ''
      id: 'negotiation'
      name: 'Negotiation Phase'
      parameters: { phase: 'negotiation'
      dependencies: ['initialize'
      status: ''
      id: 'planning'
      name: 'Planning Phase'
      parameters: { phase: 'planning'
      dependencies: ['negotiation'
      status: ''
      id: 'order-generation'
      name: 'Order Generation'
      parameters: { phase: 'order-generation'
      dependencies: ['planning'
      status: ''
      id: 'state-update'
      name: 'State Update'
      parameters: { phase: 'state-update'
      dependencies: ['order-generation'
      status: ''
      id: 'memory-consolidation'
      name: 'Memory Consolidation'
      parameters: { phase: 'memory-consolidation'
      dependencies: ['state-update'
      status: ''