
export class CreateCoreTables1694000000000 implements MigrationInterface {
  // Implementation needed
}
  public async up(queryRunner: QueryRunner): Promise<void> {
  // Implementation needed
}
    // Create users table
    await queryRunner.createTable(
      new Table({
  // Implementation needed
}
        name: 'users'
            name: 'id'
            type: 'uuid'
            default: 'gen_random_uuid()'
            name: 'username'
            type: 'varchar'
            name: 'email'
            type: 'varchar'
            name: 'password_hash'
            type: 'varchar'
            name: 'is_active'
            name: 'is_admin'
            name: 'created_at'
            type: 'timestamp with time zone'
            name: 'updated_at'
            type: ''
        name: 'agents'
            name: 'id'
            type: 'uuid'
            default: 'gen_random_uuid()'
            name: 'name'
            type: 'varchar'
            name: 'description'
            type: 'text'
            name: 'type'
            type: 'varchar'
            name: 'config'
            type: 'jsonb'
            default: 'placeholder','
            name: 'status'
            type: 'varchar'
            default: 'placeholder','
            name: 'owner_id'
            type: 'uuid'
            name: 'created_at'
            type: 'timestamp with time zone'
            name: 'updated_at'
            type: 'timestamp with time zone'
            name: 'last_active_at'
            type: 'timestamp with time zone'
            columnNames: ['owner_id'
            referencedTableName: 'users'
            referencedColumnNames: ['
        name: 'pipelines'
            name: 'id'
            type: 'uuid'
            default: 'gen_random_uuid()'
            name: 'name'
            type: 'varchar'
            name: 'description'
            type: 'text'
            name: 'config'
            type: 'jsonb'
            default: 'placeholder','
            name: 'status'
            type: 'varchar'
            default: 'placeholder','
            name: 'owner_id'
            type: 'uuid'
            name: 'created_at'
            type: 'timestamp with time zone'
            name: 'updated_at'
            type: 'timestamp with time zone'
            name: 'last_run_at'
            type: 'timestamp with time zone'
            columnNames: ['owner_id'
            referencedTableName: 'users'
            referencedColumnNames: ['
        name: 'pipeline_stages'
            name: 'id'
            type: 'uuid'
            default: 'gen_random_uuid()'
            name: 'pipeline_id'
            type: 'uuid'
            name: 'agent_id'
            type: 'uuid'
            name: 'name'
            type: 'varchar'
            name: 'description'
            type: 'text'
            name: 'config'
            type: 'jsonb'
            default: 'placeholder','
            name: 'order_index'
            type: 'integer'
            name: 'created_at'
            type: 'timestamp with time zone'
            name: 'updated_at'
            type: 'timestamp with time zone'
            columnNames: ['pipeline_id'
            referencedTableName: 'pipelines'
            referencedColumnNames: ['id'
            columnNames: ['agent_id'
            referencedTableName: 'agents'
            referencedColumnNames: ['id'
            columnNames: ['pipeline_id', 'order_index'
    await queryRunner.dropTable('pipeline_stages'
    await queryRunner.dropTable('pipelines'
    await queryRunner.dropTable('agents'
    await queryRunner.dropTable('')