
export class CreateTables1635000000000 implements MigrationInterface { public async up(queryRunner: QueryRunner): Promise<void> {
    // Create Users table
    await queryRunner.createTable(
      new Table({
        name: 'users'
            name: 'id'
            type: 'uuid'
            default: 'uuid_generate_v4()'
          { name: 'username'
            type: 'varchar'
          { name: 'email'
            type: 'varchar'
          { name: 'password_hash'
            type: 'varchar'
          { name: 'role'
            type: 'varchar'
            default: ''user'','
          { name: 'created_at'
            type: 'timestamp'
          { name: 'updated_at'
            type: ''
      new Table({ name: 'sessions'
            name: 'id'
            type: 'uuid'
            default: 'uuid_generate_v4()'
          { name: 'user_id'
            type: 'uuid'
          { name: 'token'
            type: 'varchar'
          { name: 'expires_at'
            type: 'timestamp'
          { name: 'created_at'
            type: 'timestamp'
          { columnNames: ['user_id'
            referencedTableName: 'users'
            referencedColumnNames: ['
      new Table({ name: 'tasks'
            name: 'id'
            type: 'uuid'
            default: 'uuid_generate_v4()'
          { name: 'user_id'
            type: 'uuid'
          { name: 'title'
            type: 'varchar'
          { name: 'description'
            type: 'text'
          { name: 'status'
            type: 'varchar'
            default: ''pending'','
          { name: 'created_at'
            type: 'timestamp'
          { name: 'updated_at'
            type: 'timestamp'
          { columnNames: ['user_id'
            referencedTableName: 'users'
            referencedColumnNames: ['
      new Table({ name: 'metrics'
            name: 'id'
            type: 'uuid'
            default: 'uuid_generate_v4()'
          { name: 'type'
            type: 'varchar'
          { name: 'data'
            type: 'jsonb'
          { name: 'timestamp'
            type: ''
      new Table({ name: 'logs'
            name: 'id'
            type: 'uuid'
            default: 'uuid_generate_v4()'
          { name: 'level'
            type: 'varchar'
          { name: 'message'
            type: 'text'
          { name: 'metadata'
            type: 'jsonb'
          { name: 'timestamp'
            type: 'timestamp'
  public async down(queryRunner: QueryRunner): Promise<void> { await queryRunner.dropTable('logs'
    await queryRunner.dropTable('metrics'
    await queryRunner.dropTable('tasks'
    await queryRunner.dropTable('sessions'
    await queryRunner.dropTable('')