#!/usr/bin/env python3
"""
TNF WebSocket Monitor - Generated by Gemini CLI
Connects to relay and prints all messages for debugging.
"""

import websocket
import time

def on_message(ws, message):
    print(message)

def on_error(ws, error):
    pass

def on_close(ws, close_status_code, close_msg):
    pass

def run_client():
    while True:
        try:
            ws = websocket.WebSocketApp(
                "ws://localhost:3000/ws",
                on_message=on_message,
                on_error=on_error,
                on_close=on_close
            )
            ws.run_forever()
        except Exception:
            pass
        time.sleep(5)

if __name__ == "__main__":
    run_client()
