#!/usr/bin/env python3
"""
audio_trigger_test.py — Real-time high-speed spectral matching test
Generated by Gemini CLI
"""
import ctypes
import os
import time
import numpy as np
import pyaudio

# Load the forged native module
SO_PATH = os.path.join(os.path.dirname(__file__), "native/audio_spectral_matcher.so")
lib = ctypes.CDLL(SO_PATH)

# Setup C types
lib.create_analyzer.restype = ctypes.c_void_p
lib.create_analyzer.argtypes = [ctypes.c_int]

lib.destroy_analyzer.argtypes = [ctypes.c_void_p]

lib.check_frequency.restype = ctypes.c_bool
lib.check_frequency.argtypes = [ctypes.c_void_p, ctypes.POINTER(ctypes.c_float), ctypes.c_int, ctypes.c_float]

lib.get_peak_bin.restype = ctypes.c_int
lib.get_peak_bin.argtypes = [ctypes.c_void_p, ctypes.POINTER(ctypes.c_float)]

# Audio Parameters
FORMAT = pyaudio.paFloat32
CHANNELS = 1
RATE = 44100
CHUNK = 1024 # Buffer size for FFT

def run_live_test():
    print("[👂] Initializing Native Audio Trigger...")
    p = pyaudio.PyAudio()
    
    # Initialize forged analyzer
    analyzer = lib.create_analyzer(CHUNK)
    
    stream = p.open(format=FORMAT,
                    channels=CHANNELS,
                    rate=RATE,
                    input=True,
                    frames_per_buffer=CHUNK)

    print(f"[👂] Listening (Rate: {RATE}Hz, Chunk: {CHUNK})...")
    print("      Try whistling or humming a steady tone.")
    
    try:
        last_print = time.time()
        while True:
            data = stream.read(CHUNK, exception_on_overflow=False)
            audio_data = np.frombuffer(data, dtype=np.float32)
            
            # Pointer to float data for C
            audio_ptr = audio_data.ctypes.data_as(ctypes.POINTER(ctypes.c_float))
            
            # 1. Get the peak frequency
            peak_bin = lib.get_peak_bin(analyzer, audio_ptr)
            frequency = peak_bin * (RATE / CHUNK)
            
            # 2. Check for a specific frequency trigger (e.g., 1000Hz +/- 50Hz)
            # 1000Hz is approx bin 23 for 44100/1024
            target_freq = 1000
            target_bin = int(target_freq / (RATE / CHUNK))
            
            triggered = lib.check_frequency(analyzer, audio_ptr, target_bin, 0.05)
            
            if triggered:
                print(f"[🔥] TRIGGERED: {target_freq}Hz matched! (Peak: {frequency:.1f}Hz)")
            
            if time.time() - last_print > 0.5:
                print(f"      Peak Freq: {frequency:.1f} Hz", end="\r")
                last_print = time.time()

    except KeyboardInterrupt:
        print("\n[👂] Stopping...")
    finally:
        stream.stop_stream()
        stream.close()
        p.terminate()
        lib.destroy_analyzer(analyzer)

if __name__ == "__main__":
    run_live_test()
