import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Switch } from '@/components/ui/switch';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
var EmbeddingPreference = function () {
    return (_jsx("div", { className: "container mx-auto py-6", children: _jsxs(Card, { children: [_jsx(CardHeader, { children: _jsx(CardTitle, { children: "Embedding Preferences" }) }), _jsxs(CardContent, { className: "space-y-6", children: [_jsxs("div", { className: "space-y-4", children: [_jsxs("div", { className: "space-y-2", children: [_jsx("div", { className: "text-sm font-medium", children: "Default Embedding Model" }), _jsxs(Select, { children: [_jsx(SelectTrigger, { children: _jsx(SelectValue, { placeholder: "Select model" }) }), _jsxs(SelectContent, { children: [_jsx(SelectItem, { value: "ada", children: "text-embedding-ada-002" }), _jsx(SelectItem, { value: "bge", children: "bge-large-en" }), _jsx(SelectItem, { value: "e5", children: "e5-large-v2" })] })] })] }), _jsxs("div", { className: "space-y-2", children: [_jsx("div", { className: "text-sm font-medium", children: "Embedding Dimensions" }), _jsx(Input, { type: "number", placeholder: "1536" }), _jsx("p", { className: "text-sm text-gray-500", children: "Higher dimensions may provide better accuracy but require more computational resources" })] }), _jsxs("div", { className: "space-y-2", children: [_jsx("div", { className: "text-sm font-medium", children: "Batch Size" }), _jsx(Input, { type: "number", placeholder: "32" }), _jsx("p", { className: "text-sm text-gray-500", children: "Number of texts to embed in parallel" })] }), _jsxs("div", { className: "space-y-4", children: [_jsxs("div", { className: "flex items-center space-x-2", children: [_jsx(Switch, { id: "cache-embeddings" }), _jsx("div", { className: "text-sm font-medium", children: "Cache Embeddings" })] }), _jsx("p", { className: "text-sm text-gray-500 pl-14", children: "Store embeddings in cache to improve performance for frequently accessed content" })] }), _jsxs("div", { className: "space-y-4", children: [_jsxs("div", { className: "flex items-center space-x-2", children: [_jsx(Switch, { id: "normalize-embeddings" }), _jsx("div", { className: "text-sm font-medium", children: "Normalize Embeddings" })] }), _jsx("p", { className: "text-sm text-gray-500 pl-14", children: "L2 normalize embedding vectors before storing" })] })] }), _jsxs("div", { className: "pt-4 flex justify-end space-x-2", children: [_jsx(Button, { variant: "outline", children: "Reset to Defaults" }), _jsx(Button, { children: "Save Changes" })] })] })] }) }));
};
export default EmbeddingPreference;
