import type * as PrismaTypes from '../generated/prisma';
export declare const TaskStatus: typeof PrismaTypes.TaskStatus;
export declare const TaskPriority: typeof PrismaTypes.TaskPriority;
export declare const AgentStatus: typeof PrismaTypes.AgentStatus;
export declare const AgentType: typeof PrismaTypes.AgentType;
export declare const UserRole: typeof PrismaTypes.UserRole;
export declare const WorkflowStatus: typeof PrismaTypes.WorkflowStatus;
export declare const WorkflowExecutionStatus: typeof PrismaTypes.WorkflowExecutionStatus;
export declare const PrismaClient: typeof PrismaTypes.PrismaClient;
export { Prisma } from '../generated/prisma';
export type Agent = PrismaTypes.Agent;
export type Task = PrismaTypes.Task;
export type User = PrismaTypes.User;
export type Workflow = PrismaTypes.Workflow;
export type WorkflowExecution = PrismaTypes.WorkflowExecution;
export type TaskStatus = PrismaTypes.TaskStatus;
export type TaskPriority = PrismaTypes.TaskPriority;
export type AgentStatus = PrismaTypes.AgentStatus;
export type AgentType = PrismaTypes.AgentType;
export type UserRole = PrismaTypes.UserRole;
export type WorkflowStatus = PrismaTypes.WorkflowStatus;
export type WorkflowExecutionStatus = PrismaTypes.WorkflowExecutionStatus;
//# sourceMappingURL=types.d.ts.map