export const contractConfig = {
  network: import.meta.env.VITE_CHAIN_NETWORK || 'base',
  chainId: Number(import.meta.env.VITE_CHAIN_ID || '8453'),
  rpcUrl: import.meta.env.VITE_CHAIN_RPC_URL || 'https://mainnet.base.org',
  address: {
    token: import.meta.env.VITE_CONTRACT_TOKEN || '0x0000000000000000000000000000000000000000',
    merkaba: import.meta.env.VITE_CONTRACT_MERKABA || '0x0000000000000000000000000000000000000000',
    genesis: import.meta.env.VITE_CONTRACT_GENESIS || '0x0000000000000000000000000000000000000000',
    engine: import.meta.env.VITE_CONTRACT_ENGINE || '0x0000000000000000000000000000000000000000',
    sidepotManager:
      import.meta.env.VITE_CONTRACT_SIDEPOT_MANAGER || '0x0000000000000000000000000000000000000000',
    prizeHookRouter:
      import.meta.env.VITE_CONTRACT_PRIZE_HOOK_ROUTER ||
      '0x0000000000000000000000000000000000000000',
  },
  abi: {
    ERC20: [
      'function approve(address spender, uint256 amount) external returns (bool)',
      'function allowance(address owner, address spender) external view returns (uint256)',
      'function balanceOf(address account) external view returns (uint256)',
      'function transfer(address to, uint256 amount) external returns (bool)',
      'function transferFrom(address from, address to, uint256 amount) external returns (bool)',
      'function name() external view returns (string)',
      'function symbol() external view returns (string)',
      'function decimals() external view returns (uint8)',
      'function totalSupply() external view returns (uint256)',
    ],
    MerkabaCore: [
      'function paymentToken() external view returns (address)',
      'function sunBalance() external view returns (uint256)',
      'function earthBalance() external view returns (uint256)',
      'function targetRatio() external view returns (uint256)',
      'function rebalanceStrength() external view returns (uint256)',
      'function injectCapital(uint256 _amount) external',
      'function pulse() external',
      'function payoutWinner(address _winner, uint256 _amount) external',
      'function investEarth(address _yieldStrategy, uint256 _amount) external',
      'event Deposit(string source, uint256 amount, uint256 splitSun, uint256 splitEarth)',
      'event Pulse(string action, uint256 amountMoved, uint256 newSun, uint256 newEarth)',
    ],
    GenesisNode: [
      'function paymentToken() external view returns (address)',
      'function MAX_SUPPLY() external view returns (uint256)',
      'function SUN_NODES() external view returns (uint256)',
      'function EARTH_NODES() external view returns (uint256)',
      'function totalSunRewardsPerNode() external view returns (uint256)',
      'function totalEarthRewardsPerNode() external view returns (uint256)',
      'function claimedAmount(uint256 tokenId) external view returns (uint256)',
      'function mintGenesis() external',
      'function depositSunRewards(uint256 _amount) external',
      'function depositEarthRewards(uint256 _amount) external',
      'function claimDividends(uint256 _tokenId) external',
      'function getClaimable(uint256 _tokenId) external view returns (uint256)',
      'function ownerOf(uint256 tokenId) external view returns (address)',
      'function balanceOf(address owner) external view returns (uint256)',
      'event DividendsDeposited(string sourceType, uint256 totalAmount)',
      'event DividendsClaimed(uint256 indexed tokenId, address indexed owner, uint256 amount)',
    ],
    AuctionEngine: [
      'function arcadeToken() external view returns (address)',
      'function merkabaCore() external view returns (address)',
      'function genesisNode() external view returns (address)',
      'function auctionCount() external view returns (uint256)',
      'function auctions(uint256) external view returns (uint256 id, string agentId, uint256 currentPrice, uint256 floorPrice, uint256 priceDrop, uint256 bidFee, bool active, address winner, address lastBidder, uint256 endTime)',
      'function userVolume(address) external view returns (uint256)',
      'function createCabinet(string _agentId, uint256 _startPrice, uint256 _floorPrice, uint256 _priceDrop, uint256 _bidFee) external',
      'function insertCoin(uint256 _auctionId) external',
      'function unlockAgent(uint256 _auctionId) external',
      'event CabinetCreated(uint256 indexed id, string agentId, uint256 startPrice)',
      'event CoinInserted(uint256 indexed id, address indexed player, uint256 newPrice, uint256 treasuryInjection)',
      'event JackpotUnlock(uint256 indexed id, address indexed winner, uint256 finalCost)',
    ],
    SidepotManager: [
      'function router() external view returns (address)',
      'function potCount() external view returns (uint256)',
      'function pots(uint256) external view returns (string label, uint256 balance, uint256 minDrawAmount, uint256 totalFunded, bool active)',
      'function weightedLossUnits(uint256, address) external view returns (uint256)',
      'function fundPot(uint256 potId, uint256 amount) external',
      'event PotCreated(uint256 indexed potId, string label, uint256 minDrawAmount)',
      'event PotFunded(uint256 indexed potId, address indexed funder, uint256 amount)',
      'event PotDrawn(uint256 indexed potId, address indexed winner, uint256 amount)',
      'event PotSiphoned(uint256 indexed fromPotId, uint256 indexed toPotId, uint256 amount)',
      'event LossReported(uint256 indexed potId, address indexed account, uint256 lossUnits)',
    ],
    PTPrizeHookRouter: [
      'function prizeVault() external view returns (address)',
      'function treasury() external view returns (address)',
      'function sidepotId() external view returns (uint256)',
      'function sidepotBps() external view returns (uint16)',
      'function treasuryBps() external view returns (uint16)',
      'function setSplitConfig(uint16 _sidepotBps, uint16 _treasuryBps) external',
      'event PrizeRouted(address indexed winner, uint256 prizeAmount, uint256 winnerAmount, uint256 treasuryAmount, uint256 sidepotAmount)',
      'event SplitConfigUpdated(uint16 sidepotBps, uint16 treasuryBps)',
    ],
  },
};
