export const contractConfig = {
  network: 'localhost',
  chainId: 31337,
  rpcUrl: 'http://127.0.0.1:8545',
  address: {
    token: '0x5FbDB2315678afecb367f032d93F642f64180aa3',
    merkaba: '0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512',
    genesis: '0x9fE46736679d2D9a65F0992F2272dE9f3c7fa6e0',
    engine: '0xCf7Ed3AccA5a467e9e704C703E8D87F634fB0Fc9',
  },
  abi: {
    ERC20: [
      'function approve(address spender, uint256 amount) external returns (bool)',
      'function allowance(address owner, address spender) external view returns (uint256)',
      'function balanceOf(address account) external view returns (uint256)',
      'function transfer(address to, uint256 amount) external returns (bool)',
      'function transferFrom(address from, address to, uint256 amount) external returns (bool)',
      'function name() external view returns (string)',
      'function symbol() external view returns (string)',
      'function decimals() external view returns (uint8)',
      'function totalSupply() external view returns (uint256)',
    ],
    MerkabaCore: [
      'function paymentToken() external view returns (address)',
      'function sunBalance() external view returns (uint256)',
      'function earthBalance() external view returns (uint256)',
      'function targetRatio() external view returns (uint256)',
      'function rebalanceStrength() external view returns (uint256)',
      'function injectCapital(uint256 _amount) external',
      'function pulse() external',
      'function payoutWinner(address _winner, uint256 _amount) external',
      'function investEarth(address _yieldStrategy, uint256 _amount) external',
      'event Deposit(string source, uint256 amount, uint256 splitSun, uint256 splitEarth)',
      'event Pulse(string action, uint256 amountMoved, uint256 newSun, uint256 newEarth)',
    ],
    GenesisNode: [
      'function paymentToken() external view returns (address)',
      'function MAX_SUPPLY() external view returns (uint256)',
      'function SUN_NODES() external view returns (uint256)',
      'function EARTH_NODES() external view returns (uint256)',
      'function totalSunRewardsPerNode() external view returns (uint256)',
      'function totalEarthRewardsPerNode() external view returns (uint256)',
      'function claimedAmount(uint256 tokenId) external view returns (uint256)',
      'function mintGenesis() external',
      'function depositSunRewards(uint256 _amount) external',
      'function depositEarthRewards(uint256 _amount) external',
      'function claimDividends(uint256 _tokenId) external',
      'function getClaimable(uint256 _tokenId) external view returns (uint256)',
      'function ownerOf(uint256 tokenId) external view returns (address)',
      'function balanceOf(address owner) external view returns (uint256)',
      'event DividendsDeposited(string sourceType, uint256 totalAmount)',
      'event DividendsClaimed(uint256 indexed tokenId, address indexed owner, uint256 amount)',
    ],
    AuctionEngine: [
      'function arcadeToken() external view returns (address)',
      'function merkabaCore() external view returns (address)',
      'function genesisNode() external view returns (address)',
      'function auctionCount() external view returns (uint256)',
      'function auctions(uint256) external view returns (uint256 id, string agentId, uint256 currentPrice, uint256 floorPrice, uint256 priceDrop, uint256 bidFee, bool active, address winner, address lastBidder, uint256 endTime)',
      'function userVolume(address) external view returns (uint256)',
      'function createCabinet(string _agentId, uint256 _startPrice, uint256 _floorPrice, uint256 _priceDrop, uint256 _bidFee) external',
      'function insertCoin(uint256 _auctionId) external',
      'function unlockAgent(uint256 _auctionId) external',
      'event CabinetCreated(uint256 indexed id, string agentId, uint256 startPrice)',
      'event CoinInserted(uint256 indexed id, address indexed player, uint256 newPrice, uint256 treasuryInjection)',
      'event JackpotUnlock(uint256 indexed id, address indexed winner, uint256 finalCost)',
    ],
  },
};
