import fs from 'node:fs';
import path from 'node:path';
import { ContextLogCard } from '../types/events';

const AGENT_CONTEXT_DIR = 'agent-context-cards';

export class WikiIndexUpdater {
  private readonly wikiRoot: string;
  private readonly indexPath: string;
  private debounceTimer: ReturnType<typeof setTimeout> | null = null;
  private readonly debounceMs: number;

  constructor(wikiRoot: string, debounceMs = 2000) {
    this.wikiRoot = wikiRoot;
    this.indexPath = path.join(wikiRoot, 'INDEX.md');
    this.debounceMs = debounceMs;
  }

  onCardWritten(_card: ContextLogCard): void {
    if (this.debounceTimer) {
      clearTimeout(this.debounceTimer);
    }
    this.debounceTimer = setTimeout(() => {
      this.rebuildIndex();
      this.debounceTimer = null;
    }, this.debounceMs);
  }

  rebuildIndex(): void {
    const agentDir = path.join(this.wikiRoot, AGENT_CONTEXT_DIR);
    if (!fs.existsSync(agentDir)) {
      return;
    }

    const sections: string[] = [
      '# Context Card Index',
      '',
      '> Auto-generated by audio-trigger-kws-mvp. Updated on ' + new Date().toISOString(),
      '',
    ];

    const agentDirs = fs
      .readdirSync(agentDir, { withFileTypes: true })
      .filter((d) => d.isDirectory())
      .map((d) => d.name)
      .sort();

    let totalCards = 0;

    for (const agentSlug of agentDirs) {
      const agentPath = path.join(agentDir, agentSlug);
      const mdFiles = fs
        .readdirSync(agentPath)
        .filter((f) => f.endsWith('.md'))
        .sort();

      if (mdFiles.length === 0) {
        continue;
      }

      sections.push(`## ${agentSlug}`);
      sections.push('');

      for (const mdFile of mdFiles) {
        const useCaseSlug = mdFile.replace(/\.md$/, '');
        const fullPath = path.join(agentPath, mdFile);
        const stat = fs.statSync(fullPath);
        const lineCount = this.countLines(fullPath);
        const lastModified = stat.mtime.toISOString().slice(0, 10);

        sections.push(
          `- [[${AGENT_CONTEXT_DIR}/${agentSlug}/${useCaseSlug}|${useCaseSlug}]] ` +
            `(${lineCount} entries, last ${lastModified})`
        );
        totalCards++;
      }

      sections.push('');
    }

    sections.push(`---`);
    sections.push(`_Total: ${agentDirs.length} agents, ${totalCards} use-case cards_`);

    fs.writeFileSync(this.indexPath, sections.join('\n') + '\n', 'utf8');
  }

  private countLines(filePath: string): number {
    try {
      const content = fs.readFileSync(filePath, 'utf8');
      return content.split('\n').filter((line) => line.startsWith('## ')).length;
    } catch {
      return 0;
    }
  }
}
