[build]
builder = "NIXPACKS"
nixpacksConfigPath = "apps/api-gateway/nixpacks.toml"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyMaxRetries = 10
restartPolicyType = "ON_FAILURE"
