[build]
builder = "DOCKERFILE"
watchPaths = ["apps/api-gateway/**", "packages/**"]

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyMaxRetries = 10
restartPolicyType = "ON_FAILURE"
