import '../entities/Task.tsx';
TASK_DELETED= 'TASK_DELETED,'';
 STATUS_CHANGED= 'STATUS_CHANGED'';
 COMMENT_UPDATED= 'COMMENT_UPDATED'';
export enum TaskNotificationType { ASSIGNMENT= 'ASSIGNMENT,'';
 STATUS_CHANGE= 'STATUS_CHANGE'';
MENTIONED= 'MENTIONED,'';
 COMMENT= 'COMMENT'}';