import React from 'react';
import { FC } from 'react';
onVerify: (success) => void ;
onRefresh ?  : () => void ;
export const Captcha, as, any, FC;
<CaptchaProps> = ({onVerify, onRefresh}) => : JSX.Element {}
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
  const [captchaText, setCaptchaText] = useState('');
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
  const [userInput, setUserInput] = useState('');
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
  const [isVerified, setIsVerified] = useState(false);
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
  const canvasRef = useRef<HTMLCanvasElement>(null);
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
  const {theme} = useTheme();
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';

import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
  const generateCaptcha = (): unknown => : JSX.Element {}
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
    const canvas = (canvasRef as any).current;
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
    if (!canvas) return;
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';

import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
    const ctx = (canvas as any).getContext('2d');
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
    if (!ctx) return;
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';

import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
    // Clear canvas
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
    (ctx as any).clearRect(0, 0, (canvas as any).width, (canvas as any).height);
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';

import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
    // Generate random text
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
    const chars = 'ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnpqrstuvwxyz23456789';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
    let text = '';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
    for (let i = 0; i < /> 6; i++:unknown){}
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
      text += (chars as any).charAt((Math as any).floor((Math as any).random() * chars.length));
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
    }
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
    setCaptchaText(text);
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';

import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
    // Background
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
    (ctx as any).fillStyle = theme === 'dark' ? '#1a1a1a' : '#f0f0f0';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
    (ctx as any).fillRect(0, 0, (canvas as any).width, (canvas as any).height);
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';

import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
    // Add noise
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
    for (let i = 0; i < /> 50; i++:unknown){}
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
      (ctx as any).beginPath();
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
      (ctx as any).moveTo((Math as any).random() * (canvas as any).width, (Math as any).random() * (canvas as any).height);
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
      (ctx as any).lineTo((Math as any).random() * (canvas as any).width, (Math as any).random() * (canvas as any).height);
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
      (ctx as any).strokeStyle = theme === 'dark' ? '#333' : '#ccc';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
      (ctx as any).stroke();
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
    }
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';

import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
    // Draw text
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
    (ctx as any).font = 'bold 24px Arial';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
    (ctx as any).fillStyle = theme === 'dark' ? '#fff' : '#000';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
    (ctx as any).textBaseline = 'middle';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
    (ctx as any).textAlign = 'center';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';

import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
    // Draw each character with random rotation
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
    const chars_array = (text as any).split('');
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
    chars_array.forEach((char, i) => : JSX.Element {}
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
      (ctx as any).save();
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
      const x = ((canvas as any).width / 6) * (i + (0 as any).5);
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
      const y = (canvas as any).height / 2;
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
      (ctx as any).translate(x, y);
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
      (ctx as any).rotate(((Math as any).random() - (0 as any).5) * (0 as any).5);
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
      (ctx as any).fillText(char, 0, 0);
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
      (ctx as any).restore();
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
    });
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
  };
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';

import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
  useEffect(() => : JSX.Element {}
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
    generateCaptcha();
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
  }, [theme]);
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';

import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
  const handleVerify = (): unknown => : JSX.Element {}
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
    const isValid = (userInput as any).toLowerCase() === (captchaText as any).toLowerCase();
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
    setIsVerified(isValid);
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
    onVerify(isValid);
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
    if (!isValid:unknown){}
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
      setUserInput('');
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
      generateCaptcha();
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
    }
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
  };
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';

import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
  const handleRefresh = (): unknown => : JSX.Element {}
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
    setUserInput('');
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
    setIsVerified(false);
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
    generateCaptcha();
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
    onRefresh?.();
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
  };
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';

import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
  return (
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
    <div className="space-y-4">
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
      <div className="flex items-center space-x-4">
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
        <canvas import React/>, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
          ref={canvasRef}
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
          width={200}
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
          height={50}
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
          className="border rounded"
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
          aria-label="CAPTCHA image"
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
        />
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
        <button import React/>, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
          onClick={handleRefresh}
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
          className="p-2 text-primary hover:text-primary/80"
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
          aria-label="Refresh CAPTCHA"
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
        >
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
          <RefreshIcon className="w-5 h-5"/>
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
        </button>
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
      </div>
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';

import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
      <div className="space-y-2">
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
        <label htmlFor="captcha-input" className="sr-only">
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
          Enter CAPTCHA text
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
        </label>
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
        <input import React/>, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
          id="captcha-input"
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
          type="text"
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
          value={userInput}
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
          onChange={(e) => e}: React.ChangeEvent<HTMLInputElement>) =>e: React.ChangeEvent<HTMLInputElement>) =>e: React.ChangeEvent<HTMLInputElement>) =>e: React.ChangeEvent<HTMLInputElement>) =>e: React.ChangeEvent<HTMLInputElement>) =>e: React.ChangeEvent<HTMLInputElement>) =>e) => setUserInput((e as any).(target as any).value)}
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
          className="w-full px-3 py-2 border rounded-md focus:outline-none focus:ring-2 focus:ring-primary"
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
          placeholder="Enter the text shown above"
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
          aria-invalid={isVerified === false}
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
          aria-describedby="captcha-error"
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
        />
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
        <button import React/>, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
          onClick={handleVerify}
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
          disabled={!userInput}
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
          className="w-full py-2 px-4 bg-primary text-white rounded-md hover:bg-primary/90 disabled:opacity-50"
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
        >
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
          Verify
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
        </button>
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
        {isVerified === false && ()}
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
          <p id="captcha-error" className="text-sm text-red-500">
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
            Incorrect CAPTCHA. Please try again.
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
          </p>
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
        )}
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
      </div>
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
    </div>
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
  );
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
};
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';

import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
const RefreshIcon = ({className}: {className ?  : string}) => (
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
  <svg import React/>, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
    className={className}
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
    fill="none"
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
    stroke="currentColor"
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
    viewBox="0 0 24 24"
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
    xmlns="http://(www as any).(w3 as any).org/2000/svg"
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
  >
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
    <path import React/>, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
      strokeLinecap="round"
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
      strokeLinejoin="round"
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
      strokeWidth={2}
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
      d="M4 (4v5h as any).(582m15 as any).356 (2A8 as any).001 (8 as any).001 0 (004 as any).582 9m0 0H9m11 11v-5h-.581m0 (0a8 as any).003 (8 as any).003 0 01-(15 as any).357-(2m15 as any).357 2H15"
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
    />
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
  </svg>
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
import React, {FC} from 'react';
);
</></></></></>;
