#!/bin/bash
# The New Fuse - Complete CloudRuntime Deployment Commands
# Run these commands in your terminal

echo "======================================================================"
echo "The New Fuse - CloudRuntime Deployment"
echo "======================================================================"
echo ""
echo "✅ Your CloudRuntime project has been created!"
echo "   Project URL: https://thenewfuse.com/project/453fe77c-a788-412d-8507-bc3e7bc548c3"
echo ""
echo "Follow these steps to complete deployment:"
echo ""

echo "======================================================================"
echo "STEP 1: Add PostgreSQL Database"
echo "======================================================================"
echo ""
echo "Option A - Via Dashboard (Recommended):"
echo "  1. Open: https://thenewfuse.com/project/453fe77c-a788-412d-8507-bc3e7bc548c3"
echo "  2. Click '+ New'"
echo "  3. Select 'Database' → 'PostgreSQL'"
echo "  4. Wait 30 seconds for it to provision"
echo ""
echo "Option B - Via CLI:"
echo "  Run: cloud_runtime add"
echo "  Select: Database → PostgreSQL"
echo ""
read -p "Press Enter when PostgreSQL is added..."

echo ""
echo "======================================================================"
echo "STEP 2: Deploy API Service"
echo "======================================================================"
echo ""
echo "Run these commands:"
echo ""
echo "  cd ./apps/api"
echo "  cloud_runtime up"
echo ""
echo "This will:"
echo "  - Upload your code"
echo "  - Build the Docker image (10-15 minutes)"
echo "  - Deploy the service"
echo "  - Give you a URL"
echo ""
echo "Copy the commands above and run them now."
echo ""
read -p "Press Enter when API is deployed..."

echo ""
echo "======================================================================"
echo "STEP 3: Deploy Frontend Service"
echo "======================================================================"
echo ""
echo "Run these commands:"
echo ""
echo "  cd ./apps/frontend"
echo "  cloud_runtime up"
echo ""
echo "This will build and deploy your frontend (5-10 minutes)"
echo ""
echo "Copy the commands above and run them now."
echo ""
read -p "Press Enter when Frontend is deployed..."

echo ""
echo "======================================================================"
echo "STEP 4: Configure Environment Variables"
echo "======================================================================"
echo ""
echo "Go to CloudRuntime Dashboard: https://thenewfuse.com/project/453fe77c-a788-412d-8507-bc3e7bc548c3"
echo ""
echo "For API Service:"
echo "  1. Click on the 'api' service"
echo "  2. Go to 'Variables' tab"
echo "  3. Click 'Add Variable' and add these:"
echo ""
echo "     NODE_ENV=production"
echo "     PORT=3001"
echo "     DATABASE_URL=\${{Postgres.DATABASE_URL}}"
echo "     JWT_SECRET=<generate with: openssl rand -base64 32>"
echo ""
echo "For Frontend Service:"
echo "  1. Click on the 'frontend' service"
echo "  2. Go to 'Variables' tab"
echo "  3. Add these:"
echo ""
echo "     NODE_ENV=production"
echo "     PORT=3000"
echo "     VITE_API_URL=<your-api-url-from-cloud_runtime>"
echo ""
echo "Generate JWT Secret now:"
openssl rand -base64 32
echo ""
read -p "Press Enter when environment variables are configured..."

echo ""
echo "======================================================================"
echo "STEP 5: Get Your URLs"
echo "======================================================================"
echo ""
echo "Check deployment status:"
echo "  cloud_runtime status"
echo ""
echo "View your services:"
echo "  cloud_runtime open"
echo ""
echo "Get service URLs:"
echo "  1. Go to CloudRuntime Dashboard"
echo "  2. Click on each service"
echo "  3. Go to 'Settings' → 'Domains'"
echo "  4. Copy the CloudRuntime-provided domain"
echo ""
echo "Your frontend will be accessible at the frontend domain!"
echo ""

echo "======================================================================"
echo "DEPLOYMENT COMPLETE! 🎉"
echo "======================================================================"
echo ""
echo "Next steps:"
echo "  1. Visit your frontend URL"
echo "  2. Test the application"
echo "  3. Monitor logs: cloud_runtime logs"
echo ""
echo "Useful commands:"
echo "  - View logs:      cloud_runtime logs --service api"
echo "  - Check status:   cloud_runtime status"
echo "  - Open dashboard: cloud_runtime open"
echo "  - Redeploy:       cloud_runtime up --detach"
echo ""
echo "Need help? See DEPLOYMENT_GUIDE_CLOUD_RUNTIME.md"
echo ""
